### ISSUE TITLE
[Feature Request]: the current version does not support incremental insertion, but it is very necessary！

### ISSUE THREAD

**Issue by c0derm4n** [microsoft/graphrag#1008]
### Do you need to file an issue?

- [X] I have searched the existing issues and this feature is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate feature request, not just a question. If this is a question, please use the Discussions area.

### Describe the solution you'd like

supports incremental insert, no duplicated computation or data will be added

**Comment by natoverse** [comment]
Please see #741
