### ISSUE TITLE
What is "top_level_node_id" in create_final_nodes.parquet?

### ISSUE THREAD

**Issue by MathieuNlp** [microsoft/graphrag#1058]
Hello,

I have a question regarding the "top_level_node_id" column in create_final_nodes.parquet. Is there a config to set to get the "top_level_node_id"? Because every node "id" are equal to the "top_level_node_id".
![image](https://github.com/user-attachments/assets/1c3395d7-49e7-42bd-8055-fed8d3954114)

I would like to track the hierarchy in the community but I find it hard to do it without the information of "top_level_node_id".

In my head, I see the "top_level_node_id" has the "id" of the selected supernode for each node and for each level.

Thank you for your help!

**Comment by natoverse** [comment]
It is the same value as "id". It is copied in an earlier step to facilitate a join operation on the node position compute (and should probably have been dropped for cleanliness TBH). If you would like to recreate the hierarchy for each node, you can use the "community" and "level" columns from that same table. Note that if the community column is empty for a node, it means it was not placed in a Leiden community at that level and is therefore "orphaned" (this is most common as the level increases and communities get more close-knit, excluding increasing numbers of entities that aren't quite close enough to find a home).
