### ISSUE TITLE
[Issue]: <title> In GraphRAG, in which file can the prompt for generating the final response be found?

### ISSUE THREAD

**Issue by 1024689068** [microsoft/graphrag#1062]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the issue

Hello, I’m a beginner.
while reviewing the code, I only found prompts related to information extraction but couldn’t locate the prompts for instructing the LLM to read retrieval results and generate responses. Could you please let me know which file this prompt can be found in? 
Thank you for your help.

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by AlonsoGuevara** [comment]
Hi @1024689068 

These can be found in the query code.
Relevant prompts can be found here:
- [Global Search](https://github.com/microsoft/graphrag/tree/main/graphrag/query/structured_search/global_search)
- [Local Search](https://github.com/microsoft/graphrag/tree/main/graphrag/query/structured_search/local_search)
