### ISSUE TITLE
如何在索引后的graphrag上添加新的文档？（How to add a new document on the indexed graphrag?）

### ISSUE THREAD

**Issue by minglong-huang** [microsoft/graphrag#1081]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this feature is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate feature request, not just a question. If this is a question, please use the Discussions area.

### Is your feature request related to a problem? Please describe.

不知道有没有人成功在索引后的graphrag上添加新的文档进去，希望有大佬能分享分享经验
（I don't know if anyone has successfully added a new document to the indexed graphrag. I hope someone can share their experience）

### Describe the solution you'd like

不知道有没有人成功在索引后的graphrag上添加新的文档进去，希望有大佬能分享分享经验
（I don't know if anyone has successfully added a new document to the indexed graphrag. I hope someone can share their experience）
![image](https://github.com/user-attachments/assets/11fe4521-62f2-4306-81f2-73067b830d9f)

![image](https://github.com/user-attachments/assets/a87af060-aa12-43c0-94b1-41316faeeb62)

**Comment by wade30822** [comment]
I think that you might need to reconstruct it entirely.

**Comment by wanchichang** [comment]
You can refer to [#741 ](https://github.com/microsoft/graphrag/issues/741)

**Comment by minglong-huang** [comment]
> I think that you might need to reconstruct it entirely.

Thank you, it is very useful

**Comment by minglong-huang** [comment]
> You can refer to [#741 ](https://github.com/microsoft/graphrag/issues/741)
Thank you, it is very useful

**Comment by minglong-huang** [comment]
> I think that you might need to reconstruct it entirely.

It shouldn't be necessary
