### ISSUE TITLE
[Bug]: <title>❌ create_final_entities: ❌ Errors occurred during the pipeline run, see logs for more details.

### ISSUE THREAD

**Issue by bode135** [microsoft/graphrag#1085]
### Do you need to file an issue?

- [X] I have searched the existing issues and this bug is not already filed.
- [X] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [X] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

When I use the demo:
```
# pip list | grep graphrag
# graphrag                  0.3.2

mkdir -p ./ragtest/input
curl https://www.gutenberg.org/cache/epub/24022/pg24022.txt > ./ragtest/input/book.txt
python -m graphrag.index --init --root ./ragtest

```
The graphrag occur error with:
![QQ_1725358198769](https://github.com/user-attachments/assets/13e713cd-ec7c-4f4c-930b-bc3eb60ef10f)
```
❌ create_final_entities
None
⠧ GraphRAG Indexer
├── Loading Input (text) - 1 files loaded (0 filtered) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00
├── create_base_text_units
├── create_base_extracted_entities
├── create_summarized_entities
├── create_base_entity_graph
└── create_final_entities
❌ Errors occurred during the pipeline run, see logs for more details.
```
what's wrong with it?

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by bode135** [comment]
and a very import question is, where is the logs?
```
❌ Errors occurred during the pipeline run, see logs for more details.
```

**Comment by MisterAndry** [comment]
you can find logs here :  `/ragtest/output/{timestamp}/reports`

**Comment by jackiezhangcn** [comment]
have the same issue, it seems some guys also have it.

**Comment by MisterAndry** [comment]
@bode135 @jackiezhangcn 
Could someone please submit the logs from indexing-engine.log file and your settings.yaml, otherwise no one can help you.

**Comment by Zhujing1215** [comment]
@MisterAndry Hi I had the same problem and I didn't have anything in my entity file for my catch.
[indexing-engine.log](https://github.com/user-attachments/files/16974243/indexing-engine.log)

**Comment by MisterAndry** [comment]
`13:49:46,247 graphrag.llm.base.rate_limiting_llm WARNING Process failed to invoke LLM 1/10 attempts. Cause: rate limit exceeded, will retry.`
This is what I found in your logs.
My suggestion - try to play with  **tokens_per_minute**, **requests_per_minute** parameteres, based on your chatgpt account limits.

**Comment by wwwpeirong** [comment]
I also ran into this issue the other day and just solved it. I was using SiliconFlow API for both llm and embedding models. The embedding RPM parameter should be set to 1000 (or maybe just slightly below 2000), even though officially they claim their RPM limit is 2000.

**Comment by bode135** [comment]
> @bode135 @jackiezhangcn Could someone please submit the logs from indexing-engine.log file and your settings.yaml, otherwise no one can help you.

I solved this problem last week. It seems that the log file says embedding model is wrong, and i just replace it.

**Comment by Creat-qc** [comment]
> 前几天我也遇到了这个问题，刚刚解决了它。我当时将 SiliconFlow API 用于 llm 和嵌入模型。嵌入 RPM 参数应设置为 1000（或可能略低于 2000），即使他们官方声称其 RPM 限制为 2000。

可以详细说一下解决的方式吗，比如是在哪个文件内修改的，感谢
