### ISSUE TITLE
[Bug]: Entity Graph Embedding returned as None after parsing through indexer

### ISSUE THREAD

**Issue by vrush0022** [microsoft/graphrag#1087]
### Do you need to file an issue?

- [X] I have searched the existing issues and this bug is not already filed.
- [X] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [X] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

The Node(Entity) Dataframe containing the graph embeddings when passed to `read_indexer_entities` returns a list of entities for which the field(`graph_embedding`) is None. 

On digging  deeper into the code, I noticed that the below code is the problem.
`return read_entities(
        df=entity_df,
        id_col="id",
        title_col="name",
        type_col="type",
        short_id_col="human_readable_id",
        description_col="description",
        community_col="community",
        rank_col="rank",
        name_embedding_col=None,
        description_embedding_col="description_embedding",
        graph_embedding_col=None,
        text_unit_ids_col="text_unit_ids",
        document_ids_col=None,
    )`

Here the value of `graph_embedding_col` is being passed as `None` to `read_entities`. That is the reason the field is not being read from the dataframe.
Request you to please rectify this as it is required for trying out Local Search with Graph Embedding Vectors.

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
This is the correct behavior. Graph embeddings are not used in any query method, so they are not passed to the method when used by the query library.

Graph embeddings are used for generating x/y node positions using UMAP for visualization purposes if those settings are turned on - they are off by default. See [here](https://github.com/microsoft/graphrag/discussions/697) for more info.
