### ISSUE TITLE
[Bug]: <title>输出的结果之中，中文和英文混杂

### ISSUE THREAD

**Issue by jiangyong07** [microsoft/graphrag#1089]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

我处理了一些中文材料，但通过gephi可视化之后，发现在输出的结果之中，既有中文，也有英文。

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by SliverBulle** [comment]
I've been in a similar situation, but it doesn't seem to be a problem. It will not appear in response generation. If you want the knowledge graph to be in Chinese, it is best to re-write the prompt(like entity_extraction) yourself.

**Comment by minglong-huang** [comment]
gephi可视化结果嘛？ 试试重写prompt 
试试这个模版
https://blog.csdn.net/weixin_46248339/article/details/140530006?ops_request_misc=%257B%2522request%255Fid%2522%253A%25229D96EF0A-7867-4378-88C9-339727A50FEF%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fall.%2522%257D&request_id=9D96EF0A-7867-4378-88C9-339727A50FEF&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~first_rank_ecpm_v1~rank_v31_ecpm-13-140530006-null-null.142^v100^control&utm_term=graphrag%E6%B7%BB%E5%8A%A0%E6%96%B0%E6%96%87%E6%A1%A3&spm=1018.2226.3001.4187

**Comment by jiangyong07** [comment]
谢谢！我试一下。

黄明龙 ***@***.***> 于2024年9月4日周三 13:35写道：
