### ISSUE TITLE
[Issue]:  Why does the prompt search have duplicate target content?

### ISSUE THREAD

**Issue by jyh21377063** [microsoft/graphrag#1093]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
This is an intentional prompt tuning strategy - we have found that LLM performance tends to be better when you repeat content and goals as a "reminder" to reinforce your request. With a large context window, LLMs tend to forget your original request, so we restate it.
