### ISSUE TITLE
[Feature Request]: <title> is_update_run    Incremental updates are a useful feature

### ISSUE THREAD

**Issue by qyj19920704** [microsoft/graphrag#1098]
### Do you need to file an issue?

- [X] I have searched the existing issues and this feature is not already filed.
- [X] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [X] I believe this is a legitimate feature request, not just a question. If this is a question, please use the Discussions area.

### Describe the solution you'd like

This function is very practical and is often used in projects

### Additional context

![image](https://github.com/user-attachments/assets/99d6d078-459f-4800-9d2a-9b3e3d8fafc5)

**Comment by gusye1234** [comment]
Hi, you can checkout this [repo](https://github.com/gusye1234/nano-graphrag/tree/main), it supports computing the hash of your docs and only insert the new docs.

**Comment by natoverse** [comment]
Duplicate of #741
