### ISSUE TITLE
Command not found: poe

### ISSUE THREAD

**Issue by PeterXiaTian** [microsoft/graphrag#1111]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the issue

just as the title,
when I install poetry alerady,then  "poetry run poe index --init --root .", it gives me a error.

Poetry (version 1.8.3)

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
There's not a lot we can do to troubleshoot local machine environment issues. Have you run `poetry install`? Have you tried creating a new virtual environment?
