### ISSUE TITLE
The content in the text_unit_ids column of create_final_communities.parquet doesn’t seem quite right.

### ISSUE THREAD

**Issue by DequanZhu** [microsoft/graphrag#1129]
### Do you need to file an issue?

- [X] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the issue

While reviewing the contents of create_final_communities.parquet, I noticed that for each community, the text_unit_ids is a list. Upon further inspection, I found that each element in the list is not a single UUID string but a string made up of multiple UUIDs separated by commas. Is this the expected behavior?
![image](https://github.com/user-attachments/assets/b75d93ca-a562-4b86-a036-dc337434a9b5)

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
This is correct. Communities are made up of the entities from many text units, so we store the list as "metadata" for possible backreferencing. It is not directly used, so we packed it into a single delimited string rather than a more complex normalized structure.
