### ISSUE TITLE
[Bug]: config is always loaded from the default yaml file

### ISSUE THREAD

**Issue by ddrcrow** [microsoft/graphrag#1135]
### Do you need to file an issue?

- [X] I have searched the existing issues and this bug is not already filed.
- [X] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [X] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug
graphrag                  0.3.4
whatever I specified, the config file is always the yaml file settings.yaml, I can see in the code, there is a obvious bug in load_config function. please notice the logic of the code in line, before the line there should be a 'else' I think, otherwise, any specified config path is discarded.
![image](https://github.com/user-attachments/assets/d0886984-bcaa-4abf-88a2-c4ad719e8dc5)

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by TiGaI** [comment]
Yes, I am having the same problem, this is definitely a bug on the code.

**Comment by TiGaI** [comment]
in addition, """
global_search:
  llm:
    api_key: ${GRAPHRAG_API_KEY}
    type: openai_chat # or azure_openai_chat
    model: gpt-4o-mini # mistral # local small model if need   # model: gpt-4o-
    model_supports_json: true # recommended if this is available for your model
    # max_tokens: 4000
    request_timeout: 500.0
"""

Global search config does not work, it will already use the default yaml config

**Comment by jgbradley1** [comment]
@AlonsoGuevara I believe [this PR](https://github.com/microsoft/graphrag/pull/1127) will resolve the bug once merged.

**Comment by jgbradley1** [comment]
@ddrcrow and @TiGaI, the main branch has been updated with a fix for this problem. Will close this issue for now but please re-open if you find it has not been sufficiently resolved.
