### ISSUE TITLE
[Issue]: 输出结果是否可以定制化

### ISSUE THREAD

**Issue by jiangyong07** [microsoft/graphrag#1202]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the issue

用了几次，感觉graphrag功能非常强大。但处理长文本的时候，时间花费很多，而我需要的资料相对具体。比如，我只需要某个人的相关信息：像是籍贯、生卒年、亲属关系、社会关系等。是否可以通过改写Prompt来实现定制化的输出？这样也可以节省很多时间和算力。如果可以，程序中的4个prompt该如何改写呢？

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by YepJin** [comment]
I am also looking for a solution, but you can try this one.
https://www.microsoft.com/en-us/research/blog/graphrag-auto-tuning-provides-rapid-adaptation-to-new-domains/

**Comment by jgbradley1** [comment]
The various prompts include few-shot examples of entities and relationships to look for.

After generating the prompts for the first time, you can edit the examples inside the prompts to contain only few-shot examples of the specific entity types and relationships that you’re interested in. You do not need to modify the rest of the prompt.
