### ISSUE TITLE
[Issue]: create_base_text_units show Errors occurred during the pipeline run, see logs for more details

### ISSUE THREAD

**Issue by Xiazhiguang** [microsoft/graphrag#1286]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the issue

When I ran  `poetry run poe index --root ./ragtest`, a problem occurred. IT shows "Error executing verb "create_base_text_units" in create_base_text_units: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
I got the APIKEY from there https://api.agicto.cn/v1.And i tested the apikey as the demonstration, it seems to be effective. 
This is my log information[indexing-engine.log](https://github.com/user-attachments/files/17373512/indexing-engine.log)

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
There's not much we can do to resolve connectivity or key issues. Issue #657 may have discussion for connecting to other providers.
