### ISSUE TITLE
[Bug]: Error while finding module specification for 'graphrag.index' (ModuleNotFoundError: __path__ attribute not found on 'graphrag' while trying to find 'graphrag.index')

### ISSUE THREAD

**Issue by Sere1nz** [microsoft/graphrag#1323]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

![Image](https://github.com/user-attachments/assets/9b550d23-3b4f-439e-be83-f5c1ad766c82)
/home/zzm/anaconda3/envs/nodule_detection/bin/python: Error while finding module specification for 'graphrag.index' (ModuleNotFoundError: __path__ attribute not found on 'graphrag' while trying to find 'graphrag.index')

### Steps to reproduce

conda activate <env>
python -m graphrag.index --init --root ./ragtest   

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version: 0.3.6
- Operating System: wsl
- Python Version: 3.10.0
- Related Issues:

**Comment by hodgesz** [comment]
Seeing similar issues - https://github.com/microsoft/graphrag/discussions/1327

**Comment by Sere1nz** [comment]
nvm,  The problem is that the py file name (graphrag.py) matches the package name

**Comment by soundarmoorthy** [comment]
> nvm, The problem is that the py file name (graphrag.py) matches the package name

I never thought so many people would be using this name for the client script :D
