### ISSUE TITLE
[Issue]:

### ISSUE THREAD

**Issue by anurag2506** [microsoft/graphrag#1324]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [x] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the issue

In the implementation, there is a conflict of versions between the packages 'graphrag' and 'json-repairs'. One does not support the other which is hindering the addition of graphrag to poetry. 

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Logs and screenshots

![Image](https://github.com/user-attachments/assets/fc0d7318-fdf0-45ee-a229-79967e04867c)

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by AlonsoGuevara** [comment]
HI @anurag2506 
It seems your graphrag-project is depending on json-repair ^0.30.0, but graphrag uses a lower version.

Please try reducing the target version in your graphrag-project dependencies file.

**Comment by anurag2506** [comment]
Graph tag uses a lower version of json-repair?

Or the version of graphrag should be lower than 0.3.6?
