### ISSUE TITLE
[Bug]:  (#1296) KeyError: "Column(s) ['description_embedding'] do not exist"

### ISSUE THREAD

**Issue by xxll88** [microsoft/graphrag#1345]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug
After #1296：
when increment index update ， generate_text_embeddings(graphrag) ，show 
/home/lile/graphrag/graphrag/index/update/entities.py:62 in _group_and_resolve_entities                                                              │
│                                                                                                                                                      │
│    59 │   # Group by name and resolve conflicts                                                                                                      │
│    60 │   aggregated = (                                                                                                                             │
│    61 │   │   combined.groupby("name")                                                                                                               │
│ ❱  62 │   │   .agg({                                                                                                                                 │
│    63 │   │   │   "id": "first",                                                                                                                     │
│    64 │   │   │   "type": "first",                                                                                                                   │
│    65 │   │   │   "human_readable_id": "first",         
KeyError: "Column(s) ['description_embedding'] do not exist"

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by AlonsoGuevara** [comment]
Hi @xxll88 
We had a bug on main, but it has been already addressed in the preparion for release v0.4.0

If you pull from main or update your graphrag version the issue will no longer be there :)
Thanks for your report!

**Comment by huqianghui** [comment]
I have  the same issu on Version: 0.4.1. 
There is no description_embedding column in the final_entities.parque file.
![Image](https://github.com/user-attachments/assets/4701b712-b4d9-4693-9a29-ee7f7fe61494)

**Comment by donaldNtjana** [comment]
loading 'create_final_entities.parquet' and creating description_embedding worked for me when doing 'local search'.

    # Concatenate name and description for embedding
    entity_embedding_df["name_description"] = (
        entity_embedding_df["name"] + ":" + entity_embedding_df["description"]
    )

    # Run embedding
    entity_embedding_df["description_embedding"] = embed_text(entity_embedding_df["name_description"])

**Comment by ChengIC** [comment]
I have the same issues with 0.5.0

**Comment by joycerlz** [comment]
I have the same issue, i'm using 0.5.0 and was trying to load files to neo4j

**Comment by DanielGBabel** [comment]
Im having the same issue on the 1.0.0 version.

You guys removed the column description_embeddings

[here is the index migration example](https://github.com/microsoft/graphrag/blob/main/docs/examples_notebooks/index_migration.ipynb)

```
# We renamed "name" to "title" for consistency with the rest of the tables
if "name" in final_entities.columns:
    final_entities.rename(columns={"name": "title"}, inplace=True)
remove_columns(
    final_entities, ["mname_embedding", "graph_embedding", "description_embedding"]
)
```


and you have also renamed name for  "title" now the neo4jgraph is not working properly

Please update this Neo4J guide notebook!

[](https://github.com/microsoft/graphrag/blob/main/examples_notebooks/community_contrib/neo4j/graphrag_import_neo4j_cypher.ipynb)

**Comment by xiaomujiang** [comment]
Im having the same issue on the 1.1.2 version； Please update this Neo4J guide notebook!
