### ISSUE TITLE
[Bug]: Embedding pipeline bad column name

### ISSUE THREAD

**Issue by nievespg1** [microsoft/graphrag#1355]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [x] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

There is a title variable that gets use to access the entity titles within a dataframe before embedding the descriptions for that entity. Later in the code, this variable get updated with a description causing a KeyValue error.

Here are the two lines in question:
https://github.com/microsoft/graphrag/blob/634e3ed62a6c5de7084f20e034edbb7185ad5e84/graphrag/index/operations/embed_text/embed_text.py#L180

https://github.com/microsoft/graphrag/blob/634e3ed62a6c5de7084f20e034edbb7185ad5e84/graphrag/index/operations/embed_text/embed_text.py#L196

### Steps to reproduce

Build a brand-new index

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version: 0.3.6
- Operating System: Linux
- Python Version: 3.11.5
- Related Issues:

**Comment by natoverse** [comment]
Resolved with #1356, thanks @nievespg1 !
