### ISSUE TITLE
[Bug]:ValueError: Could not find create_final_covariates.parquet in storage!

### ISSUE THREAD

**Issue by chenboju** [microsoft/graphrag#1390]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

我嘗試在0.4版本
update_index_storage: # Storage to save an updated index (for incremental indexing). Enabling this performs an incremental index run
   type: file # or blob
   base_dir: "update_output"

出現以下錯誤
![Image](https://github.com/user-attachments/assets/52f3914d-d115-45d4-b1f6-45785ff723fd)

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
This should be resolved in 0.4.1. Covariates are optional, but the first version of incremental assumed they were turned on (most of our use cases have them turned on).
