### ISSUE TITLE
[Bug]: init operate error:No module named graphrag.index.__main__; 'graphrag.index' is a package and cannot be directly executed

### ISSUE THREAD

**Issue by litaolaile** [microsoft/graphrag#1398]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

in my local env,i install python2.7 and python 3.10,i use python3 to init oper,but shows error in title,but i am sure graphrag has installed

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
GraphRAG 0.4.0+ creates a proper package, so the command becomes `graphrag init --root ./` and then `graphrag index --root ./`

**Comment by lizhinnn** [comment]
> GraphRAG 0.4.0+ creates a proper package, so the command becomes `graphrag init --root ./` and then `graphrag index --root ./`

Hello, what has become of this query command

**Comment by badspider7** [comment]
i have the same issue with `python -m graphrag init --root ./ragtest` to slove it.

**Comment by wangxu-1** [comment]
你好，请问解决了吗

**Comment by HAOYON-666** [comment]
> GraphRAG 0.4.0+ creates a proper package, so the command becomes `graphrag init --root ./` and then `graphrag index --root ./`

(graphrag) root@gz-ins-685689289084933:/gz-data/workspace/graphrag# graphrag index --root ./ragtest
Usage: graphrag index [OPTIONS]
Try 'graphrag index --help' for help.
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Invalid value for '--reporter' (env var: 'None'): <ReporterType.RICH: 'rich'> is not one of 'rich', 'print', 'none'.                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by no-more-hacks** [comment]
my problem seemed to be that i was picking up the wrong python on the path, so running python -m... was not working.

as i was running my code with poetry as the package manager, i did
`poetry run graphrag init --root ./ragtest`

and that worked. 


this was after my struggles to get graphrag to install with poetry, which i did by using the pyproject.toml file
``` 
[tool.poetry.dependencies]
python = ">=3.12,<3.13"
```

I have python 3.12 installed, and i believe that is supported by graphrag so not sure why that was needed.

**Comment by Xccc0304** [comment]
> python -m graphrag init --root ./ragtest

牛而逼之
