### ISSUE TITLE
[Feature Request]: Optional Embedding Storage in Parquet Files

### ISSUE THREAD

**Issue by IT-Bill** [microsoft/graphrag#1402]
### Do you need to file an issue?

- [x] I have searched the existing issues and this feature is not already filed.
- [x] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate feature request, not just a question. If this is a question, please use the Discussions area.

### Is your feature request related to a problem? Please describe.

In the previous version of the graphrag project, embeddings were stored directly in parquet files, which allowed for easy import into graph databases such as Neo4j and other vector store databases. However, in the new version, embeddings have been removed from the parquet files (except for the graph_embedding column). These embeddings are now generated in the final step and stored in vector stores.

While this adjustment improves workflows and the overall data architecture, it creates barriers for users who wish to import parquet files into other databases. Specifically, users would need to re-join or re-embed the text in order to recreate complete parquet files, which complicates the process of integrating with external systems.

### Describe the solution you'd like

I propose adding an optional setting in the settings.yaml configuration file that allows users to choose whether to save embeddings within the parquet files. This would enable users to maintain the flexibility of working with either the new architecture (with embeddings stored in vector stores) or the previous architecture (with embeddings stored in parquet files), depending on their specific use case.

**Comment by zangxyyds** [comment]
I encountered the same problem as well."

**Comment by zangxyyds** [comment]
I encountered the same problem as well.

**Comment by IT-Bill** [comment]
```python
OUTPUT_DIR = "./output"
LANCEDB_URI = f"{OUTPUT_DIR}/lancedb"

for parquet_name, collection_name in zip(
    ["create_final_community_reports", "create_final_entities", "create_final_text_units"],
    ["default-community-full_content", "default-entity-description", "default-text_unit-text"]
):

    # Read the parquet file
    df = pd.read_parquet(f"{OUTPUT_DIR}/{parquet_name}.parquet")

    # Connect to the vector store and retrieve results
    vs = LanceDBVectorStore(collection_name=collection_name)
    vs.connect(db_uri=LANCEDB_URI)
    results = vs.similarity_search_by_text(" ", OpenAIEmbedding().embed, k=df.shape[0])
    assert df.shape[0] == len(results)

    # Create a dictionary for fast lookup of embeddings by id
    id_emb_dict = {result.document.id: result.document.vector for result in results}

    # Assign embeddings to the 'embedding' column by matching 'id'
    df["embedding"] = df["id"].map(id_emb_dict)

    # Save the updated DataFrame back to parquet
    df.to_parquet(f"{OUTPUT_DIR}/{parquet_name}.parquet")
```
Here is the script to concatenate the original parquet files with the corresponding embeddings.
By the way, I really want to know how to retrieve all records from vector stores instead of setting a precise k or a very large k.

**Comment by natoverse** [comment]
Hi folks, with the removal of embeddings from the core data model parquets, we save a huge amount of dataframe size when loading, etc. However, we do have an option in the settings.yml that will write the embeddings out to parquet:
```yaml
snapshots:
   embeddings: true
```

This will write out the file with two columns: `id` and `embeddings`. The id can be used to join back into the matching dataframe as needed.
