### ISSUE TITLE
[Bug]: pr :Move prompts  #1404: global research --dynamic-community-selection All map responses have score 0 create_final_communities.parquet field[id] is not found in create_final_community_reports.parquet

### ISSUE THREAD

**Issue by xxll88** [microsoft/graphrag#1413]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

global research --dynamic-community-selection : (global research --no-dynamic-community-selection is ok)
the result shows  very fast: 
Warning: All map responses have score 0 (i.e., no relevant information found from the dataset), returning a canned 'I do not know' answer. You can try enabling `allow_general_knowledge` to encourage the LLM to incorporate relevant general knowledge, at the risk of increasing hallucinations.

SUCCESS: Global Search Response:
I am sorry but I am unable to answer this question given the provided data.

I found create_final_communities.parquet  field[id]:
![Image](https://github.com/user-attachments/assets/95652a50-cc27-42df-9cdd-65d5673e082a)

create_final_communities.parquet  field[id] is not equal in create_final_community_reports.parque  so context level[0]=0 ,

**Comment by eriklee1895** [comment]
I met the same problem:
`➜  graphrag_0.5.0_test graphrag query \
--root ./ragtest \
--method global \
--query "What is Transformer?" \
--dynamic-community-selection


creating llm client with {'api_key': 'REDACTED,len=56', 'type': "openai_chat", 'model': 'gpt-4o-mini', 'max_tokens': 4000, 'temperature': 0.0, 'top_p': 1.0, 'n': 1, 'request_timeout': 180.0, 'api_base': None, 'api_version': None, 'organization': None, 'proxy': None, 'audience': None, 'deployment_name': 'gpt-4o-mini', 'model_supports_json': True, 'tokens_per_minute': 0, 'requests_per_minute': 0, 'max_retries': 10, 'max_retry_wait': 10.0, 'sleep_on_rate_limit_recommendation': True, 'concurrent_requests': 25}
creating llm client with {'api_key': 'REDACTED,len=56', 'type': "openai_chat", 'model': 'gpt-4o-mini', 'max_tokens': 4000, 'temperature': 0.0, 'top_p': 1.0, 'n': 1, 'request_timeout': 180.0, 'api_base': None, 'api_version': None, 'organization': None, 'proxy': None, 'audience': None, 'deployment_name': None, 'model_supports_json': True, 'tokens_per_minute': 0, 'requests_per_minute': 0, 'max_retries': 10, 'max_retry_wait': 10.0, 'sleep_on_rate_limit_recommendation': True, 'concurrent_requests': 25}
Warning: All map responses have score 0 (i.e., no relevant information found from the dataset), returning a canned 'I do not know' answer. You can try enabling `allow_general_knowledge` to encourage the LLM to incorporate relevant general knowledge, at the risk of increasing hallucinations.

SUCCESS: Global Search Response:
I am sorry but I am unable to answer this question given the provided data.`

I confirm I use the latest graphrag index my txt source, and index success, and generated the parquet files:
![Image](https://github.com/user-attachments/assets/5e091e80-a8dd-411b-9829-d844afd7af5c)

When I query without `--dynamic-community-selection`, the answer is success.

**Comment by xxll88** [comment]
has fixed in #1450
