### ISSUE TITLE
pip install takes too long and has dependency issues

### ISSUE THREAD

**Issue by nchandhi** [microsoft/graphrag#1423]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the issue

Hi graphrag team, I have been trying to use graphrag by installing it from pypi. The installation takes up to 10 minutes (most times lot more time). I was finally able to get it to work locally in my virtual environment. But when I try to build a solution with it, I need to install and process data either through a bicep deployment script or as an azure function. This has been very painful process to build/debug/unit test because every install takes forever. The same applies to creating functions for querying. Please consider simplifying the dependencies and the time it takes to install graphrag.

### Steps to reproduce

To reproduce, please run - pip install graphrag in VScode or any choice of editor terminal.

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version: latest version or 0.3.6
- Operating System: Windows
- Python Version: 3.11
- Related Issues:

**Comment by jgbradley1** [comment]
This is just a suggestion - have you considered using [containerized azure functions](https://learn.microsoft.com/en-us/azure/azure-functions/functions-deploy-container?tabs=acr%2Cbash%2Cazure-cli&pivots=programming-language-python#create-and-configure-a-function-app-on-azure-with-the-image)? Building a based image with graphrag installed would significantly reduce your development cycle.
