### ISSUE TITLE
How to effectively reduce the cost of GraphRAG when calling LLM to process data?

### ISSUE THREAD

**Issue by crazyyanchao** [microsoft/graphrag#1429]

**Comment by jgbradley1** [comment]
The most direct way is to use a *mini* version of the OpenAI models (GPT-4o-mini vs GPT-4o for example) - they're faster and cheaper.

For a deeper dive into graphrag and cost optimization, see our most recently published [blog entry](https://www.microsoft.com/en-us/research/blog/graphrag-improving-global-search-via-dynamic-community-selection) that discusses one area where we are able to reduce cost and maintain comparable quality. More is coming though - so stay tuned!
