### ISSUE TITLE
[Bug]: DRIFT not configurable

### ISSUE THREAD

**Issue by MBRSL** [microsoft/graphrag#1432]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [x] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

Though a various parameters can be set through setting.yml, it's not working for DRIFT. For example, I wish to set lower follow ups by using:
```
...
drift_search:
  drift_k_followups: 1
```

This isn't working since DRIFTSeach doesn't read config (see below).
https://github.com/microsoft/graphrag/blob/v0.5.0/graphrag/query/factories.py#L193

DRIFTSearchContextBuilder reads from config but DRIFTSeach doesn't.

### Steps to reproduce

Step 1: Init graphrag with arbitary documents
Step 2: Modify setting.yml. Add `drift_k_followups` like the followings
```
drift_search:
  drift_k_followups: 1
```
Step 3: Index
Step 4: Ask random questions with drift search

### Expected Behavior

Expected:
In the console output, it should output 5/5 in the first phase and 1/1 in the second phase

Actual:
In the console output, it output 5/5 in the first phase and 20/20 in the second phase

### Additional Information

- GraphRAG Version: 0.5.0
- Operating System: Mac OS 14.4.1
- Python Version: 3.11.9

**Comment by natoverse** [comment]
We've added DRIFT config reading in the latest versions, please try again and let us know if it still isn't working.
