### ISSUE TITLE
[Feature Request]: Support Azure AD Token Provider in CLI

### ISSUE THREAD

**Issue by MaxwellSalmon** [microsoft/graphrag#1447]
### Do you need to file an issue?

- [x] I have searched the existing issues and this feature is not already filed.
- [x] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate feature request, not just a question. If this is a question, please use the Discussions area.

### Is your feature request related to a problem? Please describe.

Please support using `azure_ad_token_provider` in the CLI

I am unable to see how I could use `az_ad_token_provider` in the `settings.yaml` pipeline. The [docs ](https://microsoft.github.io/graphrag/config/yaml/)only mention API key.

### Describe the solution you'd like

I would like to be able to use `azure_ad_token_provider` for authentication.

**Comment by natoverse** [comment]
If you omit your API key from the config, GraphRAG fallback to using Azure managed identity. You'll need to use `az login` on the command line.

**Comment by MaxwellSalmon** [comment]
Thank you, this resolved the issue.
