### ISSUE TITLE
[Bug]: The poetry run poe query command clears the entity description data table.

### ISSUE THREAD

**Issue by xiuxiuxius** [microsoft/graphrag#1463]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [x] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

after I created the knowledge base
![Image](https://github.com/user-attachments/assets/c795b4fa-1e2c-46f9-b251-007a5671aac0)

 I used the lancedb library to query the default-entity-description table, which had 35 records. 
![Image](https://github.com/user-attachments/assets/8926e5fd-9b5c-4194-92f9-a4ac41c208f7)

Then I execute the query command, 
```bash
poetry run poe query --method local --query 长妈妈的故事
```
no results:
![Image](https://github.com/user-attachments/assets/ab41555d-7134-4382-a703-1a7887daf8c6)

after that , query the default-entity-description table again, recorded as 0.
![Image](https://github.com/user-attachments/assets/c682e8b6-3c3f-4867-86c2-0cba6997cbe8)

The poetry run poe query command seems to automatically execute the function in main. The load_documents function in lancedb.py,  was executed earlier. If overwrite value is true, the original database is overwritten, so, is empty. 
![Image](https://github.com/user-attachments/assets/70312e0a-3a9f-4b63-b519-8f28178b86b1)

So in a new query activity, after index, I change overwrite value to False in the code, and the local query has  results.
![Image](https://github.com/user-attachments/assets/6c657526-8b4c-4a05-9835-24f22bba3273)

### Steps to reproduce

1. txt document，
[txt-baicao.txt](https://github.com/user-attachments/files/17981886/txt-baicao.txt)

2. change file_type value in create_graphrag_config.py

![Image](https://github.com/user-attachments/assets/7f5a0aad-651a-481e-b4f2-c15779df2083)

3. change encoding value in text.py
![Image](https://github.com/user-attachments/assets/153c5d77-9f36-486d-b896-0e12fba51ad4)

4. change dim and json argument in lancedb.py
![Image](https://github.com/user-attachments/assets/29a55f52-c909-4a57-a04e-4bea2ddf5734)

5. exec index command:
```bash
poetry run poe index
```
7. view default-entity-description table:
```python
import lancedb

uri = "output/lancedb"
db = lancedb.connect(uri)
print(db.table_names())

table = db["default-entity-description"]
print(f"Row count: {len(table)}")
```
8. exec query command:
```bash
poetry run poe query --method local --query 长妈妈的故事
```
results will be empty
9. view default-entity-description table again:
```python
import lancedb

uri = "output/lancedb"
db = lancedb.connect(uri)
print(db.table_names())

table = db["default-entity-description"]
print(f"Row count: {len(table)}")
```
the num of records will be 0.

### Expected Behavior

what I expect: 
1. when exec **poetry run poe index**: 
The index is built normally.
2. when exec **poetry run poe query**:
does not change the index content or db table, but normal query. 

### GraphRAG Config Used

```python
# Paste your config here
# Copyright (c) 2024 Microsoft Corporation.
# Licensed under the MIT License

"""Common default configuration values."""

from pathlib import Path

from datashaper import AsyncType

from graphrag.config.enums import (
    CacheType,
    InputFileType,
    InputType,
    LLMType,
    ReportingType,
    StorageType,
    TextEmbeddingTarget,
)
from graphrag.vector_stores.factory import VectorStoreType

ASYNC_MODE = AsyncType.Threaded
ENCODING_MODEL = "cl100k_base"
#
# LLM Parameters
#
LLM_TYPE = LLMType.OpenAIChat
# LLM_MODEL = "gpt-4-turbo-preview"
LLM_MODEL = "gpt-4o-mini"
LLM_MAX_TOKENS = 4000
LLM_TEMPERATURE = 0
LLM_TOP_P = 1
LLM_N = 1
LLM_REQUEST_TIMEOUT = 180.0
LLM_TOKENS_PER_MINUTE = 0
LLM_REQUESTS_PER_MINUTE = 0
LLM_MAX_RETRIES = 10
LLM_MAX_RETRY_WAIT = 10.0
LLM_SLEEP_ON_RATE_LIMIT_RECOMMENDATION = True
LLM_CONCURRENT_REQUESTS = 25

#
# Text Embedding Parameters
#
EMBEDDING_TYPE = LLMType.OpenAIEmbedding
EMBEDDING_MODEL = "text-embedding-3-small"
EMBEDDING_BATCH_SIZE = 16
EMBEDDING_BATCH_MAX_TOKENS = 8191
EMBEDDING_TARGET = TextEmbeddingTarget.required

CACHE_TYPE = CacheType.file
CACHE_BASE_DIR = "cache"
CHUNK_SIZE = 1200
CHUNK_OVERLAP = 100
CHUNK_GROUP_BY_COLUMNS = ["id"]
CLAIM_DESCRIPTION = (
    "Any claims or facts that could be relevant to information discovery."
)
CLAIM_MAX_GLEANINGS = 1
CLAIM_EXTRACTION_ENABLED = False
MAX_CLUSTER_SIZE = 10
COMMUNITY_REPORT_MAX_LENGTH = 2000
COMMUNITY_REPORT_MAX_INPUT_LENGTH = 8000
ENTITY_EXTRACTION_ENTITY_TYPES = ["organization", "person", "geo", "event"]
ENTITY_EXTRACTION_MAX_GLEANINGS = 1
INPUT_FILE_TYPE = InputFileType.text
INPUT_TYPE = InputType.file
INPUT_BASE_DIR = "input"
INPUT_FILE_ENCODING = "utf-8"
INPUT_TEXT_COLUMN = "text"
INPUT_CSV_PATTERN = ".*\\.csv$"
INPUT_TEXT_PATTERN = ".*\\.txt$"
PARALLELIZATION_STAGGER = 0.3
PARALLELIZATION_NUM_THREADS = 50
NODE2VEC_ENABLED = False
NODE2VEC_NUM_WALKS = 10
NODE2VEC_WALK_LENGTH = 40
NODE2VEC_WINDOW_SIZE = 2
NODE2VEC_ITERATIONS = 3
NODE2VEC_RANDOM_SEED = 597832
REPORTING_TYPE = ReportingType.file
REPORTING_BASE_DIR = "logs"
SNAPSHOTS_GRAPHML = False
SNAPSHOTS_RAW_ENTITIES = False
SNAPSHOTS_TOP_LEVEL_NODES = False
SNAPSHOTS_EMBEDDINGS = False
SNAPSHOTS_TRANSIENT = False
STORAGE_BASE_DIR = "output"
STORAGE_TYPE = StorageType.file
SUMMARIZE_DESCRIPTIONS_MAX_LENGTH = 500
UMAP_ENABLED = False
UPDATE_STORAGE_BASE_DIR = "update_output"

VECTOR_STORE = f"""
    type: {VectorStoreType.LanceDB.value}
    db_uri: '{(Path(STORAGE_BASE_DIR) / "lancedb")!s}'
    container_name: default
    overwrite: true\
"""

# Local Search
LOCAL_SEARCH_TEXT_UNIT_PROP = 0.5
LOCAL_SEARCH_COMMUNITY_PROP = 0.1
LOCAL_SEARCH_CONVERSATION_HISTORY_MAX_TURNS = 5
LOCAL_SEARCH_TOP_K_MAPPED_ENTITIES = 10
LOCAL_SEARCH_TOP_K_RELATIONSHIPS = 10
LOCAL_SEARCH_MAX_TOKENS = 12_000
LOCAL_SEARCH_LLM_TEMPERATURE = 0
LOCAL_SEARCH_LLM_TOP_P = 1
LOCAL_SEARCH_LLM_N = 1
LOCAL_SEARCH_LLM_MAX_TOKENS = 2000

# Global Search
GLOBAL_SEARCH_LLM_TEMPERATURE = 0
GLOBAL_SEARCH_LLM_TOP_P = 1
GLOBAL_SEARCH_LLM_N = 1
GLOBAL_SEARCH_MAX_TOKENS = 12_000
GLOBAL_SEARCH_DATA_MAX_TOKENS = 12_000
GLOBAL_SEARCH_MAP_MAX_TOKENS = 1000
GLOBAL_SEARCH_REDUCE_MAX_TOKENS = 2_000
GLOBAL_SEARCH_CONCURRENCY = 32

# Global Search with dynamic community selection
DYNAMIC_SEARCH_LLM_MODEL = "gpt-4o-mini"
DYNAMIC_SEARCH_RATE_THRESHOLD = 1
DYNAMIC_SEARCH_KEEP_PARENT = False
DYNAMIC_SEARCH_NUM_REPEATS = 1
DYNAMIC_SEARCH_USE_SUMMARY = False
DYNAMIC_SEARCH_CONCURRENT_COROUTINES = 16
DYNAMIC_SEARCH_MAX_LEVEL = 2

# DRIFT Search
DRIFT_SEARCH_LLM_TEMPERATURE = 0
DRIFT_SEARCH_LLM_TOP_P = 1
DRIFT_SEARCH_LLM_N = 3
DRIFT_SEARCH_MAX_TOKENS = 12_000
DRIFT_SEARCH_DATA_MAX_TOKENS = 12_000
DRIFT_SEARCH_CONCURRENCY = 32

DRIFT_SEARCH_K_FOLLOW_UPS = 20
DRIFT_SEARCH_PRIMER_FOLDS = 5
DRIFT_SEARCH_PRIMER_MAX_TOKENS = 12_000

DRIFT_LOCAL_SEARCH_TEXT_UNIT_PROP = 0.9
DRIFT_LOCAL_SEARCH_COMMUNITY_PROP = 0.1
DRIFT_LOCAL_SEARCH_TOP_K_MAPPED_ENTITIES = 10
DRIFT_LOCAL_SEARCH_TOP_K_RELATIONSHIPS = 10
DRIFT_LOCAL_SEARCH_MAX_TOKENS = 12_000
DRIFT_LOCAL_SEARCH_LLM_TEMPERATURE = 0
DRIFT_LOCAL_SEARCH_LLM_TOP_P = 1
DRIFT_LOCAL_SEARCH_LLM_N = 1
DRIFT_LOCAL_SEARCH_LLM_MAX_TOKENS = 2000

DRIFT_N_DEPTH = 3

```

### Additional Information

- GraphRAG Version: 0.5.0
- Operating System:  MacOS 14.4.1
- Python Version: 3.10.14
- Related Issues: None

**Comment by natoverse** [comment]
We had a patch in place to import into lancedb within the query, in order to support older indexes. There may have been a bug in this that we were unaware of. However, with the 1.0 release we remove all back-compat patches, so there is never any loading into lancedb during query.
