### ISSUE TITLE
[Bug]: Duplicated Content in local_search_system_prompt.py

### ISSUE THREAD

**Issue by IT-Bill** [microsoft/graphrag#1484]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [x] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

The content in the local_search_system_prompt.py file appears to be duplicated. The sections for ---Goal--- and ---Target response length and format--- are repeated twice within the file. This redundancy may lead to confusion and is unnecessary.

### Steps to reproduce

1. Navigate to the graphrag/graphrag/prompts/query/local_search_system_prompt.py file.
2. Review the sections starting with ---Goal--- and ---Target response length and format---.

### Expected Behavior

The content for ---Goal--- and ---Target response length and format--- should only appear once in the local_search_system_prompt.py file.

### Additional Information

- GraphRAG Version: latest v0.9.0 still has this problem.

**Comment by IT-Bill** [comment]
Is the duplication intentional?

**Comment by MBRSL** [comment]
It could be. Since {context_data} could be pretty long, LLM may lose focus on its job. Duplicating those prompt may make LLM recall what it should do.
