### ISSUE TITLE
[Issue]: <title> Why is only this ‘graph.graphml’ generated, but not the ‘merged_graph.graphml’?

### ISSUE THREAD

**Issue by hope12122** [microsoft/graphrag#1498]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [x] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the issue

Only 'graph.graphml' exists, and 'merged_graph.graphml' is not generated. How to generate 'merged_graph.graphml'?
Only modified here, no other changes. LLM model is gpt-4o-mini.
![Image](https://github.com/user-attachments/assets/7343ca92-46c3-4cc7-977d-a5b7f9851b43)
![Image](https://github.com/user-attachments/assets/af05fcb3-4e0b-44d1-9e45-c943764f6150)

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Logs and screenshots

![Image](https://github.com/user-attachments/assets/2fd9789f-844d-4b59-a40f-23ff718264a4)
![Image](https://github.com/user-attachments/assets/b77c9177-4c45-49e7-80da-b20af68f79b3)

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
We've removed a bunch of the intermediary graphml generations (in fact, we no longer serialize any graphml, and only use nx.Graph where necessary). The graph.graphml file is only saved to disk if snapshotting is turned on, and still contains the x/y coordinates for each node if you are looking to visualize the graph. Note that this artifact is **not** a required part of the GraphRAG index.
