### ISSUE TITLE
[Bug]: Global (and local) encoding_model option is being ignored

### ISSUE THREAD

**Issue by nreinartz** [microsoft/graphrag#1499]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [x] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

The global `encoding_model` option is ignored when constructing the LLMParameters for the root llm and all sub llm options. In fact this option is even ignored if it is set explicitly for each section. This leads to the wrong tokenizer being used while indexing. 

Possible fix: The create_graphrag_config function needs to set all encoding_model (local > global > default) options when initializing LLMParameters models.

### Steps to reproduce

Init a new project via the latest (0.9.0) graphrag version, edit the global encoding_model option in the settings.yaml, run the index command. Have a look at the config dump in the console. All (except the global) encoding_model options will have the default "cl100k_base" entry.

### Expected Behavior

The global option should overwrite the default one if set.

### GraphRAG Config Used

```yaml
encoding_model: o200k_base

...
```

### Additional Information

- GraphRAG Version: 0.9.0
- Operating System: Windows 10, Ubuntu 24.04
- Python Version: 3.12
- Related Issues: None

**Comment by natoverse** [comment]
We believe this was a bug introducing during our adoption of fnllm as the underlying LLM library. We just pushed out a 1.0.1 patch today, please let if know if your problem still exists with that version.
