### ISSUE TITLE
[Issue]: <title> Unable to create the index properly！！

### ISSUE THREAD

**Issue by kiedeng** [microsoft/graphrag#1568]
help！！help！！！
### Describe the issue

When using `graphrag index --root ./ragtest` to create a knowledge graph, it gets stuck at one point:  

```  
⠋ GraphRAG Indexer  
├── Loading Input (InputFileType.text) - 1 files loaded (0 filtered) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00  
├── create_base_text_units  
├── create_final_documents  
└── extract_graph  
    └── Verb extract_graph ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--  
```

（**This issue occurs in version 1.0.1, but it works fine in version 0.5**）

**Error logs after tens of minutes:**
```
23:35:36,614 graphrag.index.graph.extractors.graph.graph_extractor ERROR error extracting graph
Traceback (most recent call last):
  File "/home/atguigu/anaconda3/envs/grap2/lib/python3.11/site-packages/graphrag/index/graph/extractors/graph/graph_extractor.py", line 127, in __call__
    result = await self._process_document(text, prompt_variables)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atguigu/anaconda3/envs/grap2/lib/python3.11/site-packages/graphrag/index/graph/extractors/graph/graph_extractor.py", line 155, in _process_document
    response = await self._llm(
               ^^^^^^^^^^^^^^^^
  File "/home/atguigu/anaconda3/envs/grap2/lib/python3.11/site-packages/fnllm/openai/llm/chat.py", line 83, in __call__
    return await self._text_chat_llm(prompt, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atguigu/anaconda3/envs/grap2/lib/python3.11/site-packages/fnllm/openai/llm/features/tools_parsing.py", line 120, in __call__
    return await self._delegate(prompt, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atguigu/anaconda3/envs/grap2/lib/python3.11/site-packages/fnllm/base/base.py", line 112, in __call__
    return await self._invoke(prompt, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atguigu/anaconda3/envs/grap2/lib/python3.11/site-packages/fnllm/base/base.py", line 128, in _invoke
    return await self._decorated_target(prompt, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atguigu/anaconda3/envs/grap2/lib/python3.11/site-packages/fnllm/services/json.py", line 71, in invoke
    return await delegate(prompt, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atguigu/anaconda3/envs/grap2/lib/python3.11/site-packages/fnllm/services/retryer.py", line 109, in invoke
    result = await execute_with_retry()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atguigu/anaconda3/envs/grap2/lib/python3.11/site-packages/fnllm/services/retryer.py", line 106, in execute_with_retry
    raise RetriesExhaustedError(name, self._max_retries)
fnllm.services.errors.RetriesExhaustedError: Operation 'chat' failed - 10 retries exhausted.
```

**Comment by unirain** [comment]
I'm the same, I tried downgrading to 1.0.0 but it didn't work

**Comment by kiedeng** [comment]
> I'm the same, I tried downgrading to 1.0.0 but it didn't work我是一样的，我尝试降级到 1.0.0，但不起作用


Feeling upset.I also tried version 0.9, but it didn’t work. Only versions 0.5 and below work.

**Comment by kebuAAA** [comment]
> > I'm the same, I tried downgrading to 1.0.0 but it didn't work我是一样的，我尝试降级到 1.0.0，但不起作用
> 
> Feeling upset.I also tried version 0.9, but it didn’t work. Only versions 0.5 and below work.

have you solved this problem? I tried to build a local service but have nothing known about how to use the fnllm module.  It seems that this module would change the final request url which is not same as the `api_base` I configed

**Comment by kiedeng** [comment]
> have you solved this problem? I tried to build a local service but have nothing known about how to use the fnllm module. It seems that this module would change the final request url which is not same as the `api_base` I configed

Not resolved, no idea where to start.

**Comment by unirain** [comment]
I solved it, I used the environment variable
os.environ["OPENAI_BASE_URL"] ='your url ' /v1
have a try

**Comment by kebuAAA** [comment]
> I solved it, I used the environment variable os.environ["OPENAI_BASE_URL"] ='your url ' /v1 have a try [@kiedeng](https://github.com/kiedeng) [@kebuAAA](https://github.com/kebuAAA)

a little confused,where should i put this line. I use the commandline to run index

**Comment by unirain** [comment]
> > I solved it, I used the environment variable os.environ["OPENAI_BASE_URL"] ='your url ' /v1 have a try [@kiedeng](https://github.com/kiedeng) [@kebuAAA](https://github.com/kebuAAA)
> 
> 有点困惑，这行应该放哪儿呢。我使用命令行运行 index

export OPENAI_BASE_URL='your url' /v1

**Comment by kiedeng** [comment]
> I solved it, I used the environment variable我解决了它，我使用了环境变量 os.environ["OPENAI_BASE_URL"] ='your url ' /v1os.environ["OPENAI_BASE_URL"] = 'your url ' /v1 os.environ["OPENAI_BASE_URL"] = '您的 URL' /v1os.environ["OPENAI_BASE_URL"] = 'your url ' /v1 os.environ["OPENAI_BASE_URL"] = '您的 URL' /v1 have a try  试一试 [@kiedeng](https://github.com/kiedeng) [@kebuAAA](https://github.com/kebuAAA)

Good job，very nice！！！

How did you find this piece of code? I couldn't locate it during debugging. So sad.

**Comment by kebuAAA** [comment]
> > I solved it, I used the environment variable我解决了它，我使用了环境变量 os.environ["OPENAI_BASE_URL"] ='your url ' /v1os.environ["OPENAI_BASE_URL"] = 'your url ' /v1 os.environ["OPENAI_BASE_URL"] = '您的 URL' /v1os.environ["OPENAI_BASE_URL"] = 'your url ' /v1 os.environ["OPENAI_BASE_URL"] = '您的 URL' /v1 have a try  试一试 [@kiedeng](https://github.com/kiedeng) [@kebuAAA](https://github.com/kebuAAA)
> 
> Good job，very nice！！！
> 
> How did you find this piece of code? I couldn't locate it during debugging. So sad.

can you share you config file with me? I can't solve it😭

**Comment by kebuAAA** [comment]
> I solved it, I used the environment variable os.environ["OPENAI_BASE_URL"] ='your url ' /v1 have a try [@kiedeng](https://github.com/kiedeng) [@kebuAAA](https://github.com/kebuAAA)

I succeed by using this method, many thanks for your kind help.

**Comment by dneprovets** [comment]
❯ export OPENAI_BASE_URL='your url' '/v1'
export: not valid in this context: /v1


could you pls explain more specific the way how could you solved the issue?

**Comment by kiedeng** [comment]
> ❯ export OPENAI_BASE_URL='your url' '/v1' export: not valid in this context: /v1
> 
> could you pls explain more specific the way how could you solved the issue?

Before running `graphrag index --root ./ragtest`, reset the global variables.  

- If you are using Linux, run:  
  ```bash
  export OPENAI_BASE_URL='your url' /v1
  ```

- If you are using Windows, run:  
  ```cmd
  set OPENAI_BASE_URL=your url
  ```

**Comment by nilin1998** [comment]
> > ❯ export OPENAI_BASE_URL='your url' '/v1' export: not valid in this context: /v1❯ export OPENAI_BASE_URL='your url' '/v1' export： 在此上下文中无效： /v1
> > could you pls explain more specific the way how could you solved the issue?您能否更具体地解释一下您如何解决这个问题的方法？
> 
> Before running `graphrag index --root ./ragtest`, reset the global variables.在运行 `graphrag index --root ./ragtest` 之前，请重置全局变量。
> 
> * If you are using Linux, run:如果您使用的是 Linux，请运行：
>   export OPENAI_BASE_URL='your url' /v1
> * If you are using Windows, run:如果您使用的是 Windows，请运行：
>   set OPENAI_BASE_URL=your url

I tried to solve it according to your method, but the same error still occurred.
My log is：
15:15:16,273 httpx INFO HTTP Request: POST http://127.0.0.1:9997/v1/chat/completions "HTTP/1.1 502 Bad Gateway"
15:15:16,277 graphrag.index.graph.extractors.graph.graph_extractor ERROR error extracting graph
Traceback (most recent call last):
  File "C:\Anaconda\envs\graphrag\Lib\site-packages\graphrag\index\graph\extractors\graph\graph_extractor.py", line 127, in __call__
    result = await self._process_document(text, prompt_variables)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\envs\graphrag\Lib\site-packages\graphrag\index\graph\extractors\graph\graph_extractor.py", line 155, in _process_document
    response = await self._llm(
               ^^^^^^^^^^^^^^^^
  File "C:\Anaconda\envs\graphrag\Lib\site-packages\fnllm\openai\llm\chat.py", line 83, in __call__
    return await self._text_chat_llm(prompt, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\envs\graphrag\Lib\site-packages\fnllm\openai\llm\features\tools_parsing.py", line 120, in __call__
    return await self._delegate(prompt, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\envs\graphrag\Lib\site-packages\fnllm\base\base.py", line 112, in __call__
    return await self._invoke(prompt, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\envs\graphrag\Lib\site-packages\fnllm\base\base.py", line 128, in _invoke
    return await self._decorated_target(prompt, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\envs\graphrag\Lib\site-packages\fnllm\services\json.py", line 71, in invoke
    return await delegate(prompt, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\envs\graphrag\Lib\site-packages\fnllm\services\retryer.py", line 109, in invoke
    result = await execute_with_retry()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\envs\graphrag\Lib\site-packages\fnllm\services\retryer.py", line 106, in execute_with_retry
    raise RetriesExhaustedError(name, self._max_retries)

**Comment by kebuAAA** [comment]
> > > ❯ export OPENAI_BASE_URL='your url' '/v1' export: not valid in this context: /v1❯ export OPENAI_BASE_URL='your url' '/v1' export： 在此上下文中无效： /v1
> > > could you pls explain more specific the way how could you solved the issue?您能否更具体地解释一下您如何解决这个问题的方法？
> > 
> > 
> > Before running `graphrag index --root ./ragtest`, reset the global variables.在运行 `graphrag index --root ./ragtest` 之前，请重置全局变量。
> > 
> > * If you are using Linux, run:如果您使用的是 Linux，请运行：
> >   export OPENAI_BASE_URL='your url' /v1
> > * If you are using Windows, run:如果您使用的是 Windows，请运行：
> >   set OPENAI_BASE_URL=your url
> 
> I tried to solve it according to your method, but the same error still occurred. My log is： 15:15:16,273 httpx INFO HTTP Request: POST http://127.0.0.1:9997/v1/chat/completions "HTTP/1.1 502 Bad Gateway" 15:15:16,277 graphrag.index.graph.extractors.graph.graph_extractor ERROR error extracting graph Traceback (most recent call last): File "C:\Anaconda\envs\graphrag\Lib\site-packages\graphrag\index\graph\extractors\graph\graph_extractor.py", line 127, in **call** result = await self._process_document(text, prompt_variables) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Anaconda\envs\graphrag\Lib\site-packages\graphrag\index\graph\extractors\graph\graph_extractor.py", line 155, in _process_document response = await self._llm( ^^^^^^^^^^^^^^^^ File "C:\Anaconda\envs\graphrag\Lib\site-packages\fnllm\openai\llm\chat.py", line 83, in **call** return await self._text_chat_llm(prompt, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Anaconda\envs\graphrag\Lib\site-packages\fnllm\openai\llm\features\tools_parsing.py", line 120, in **call** return await self._delegate(prompt, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Anaconda\envs\graphrag\Lib\site-packages\fnllm\base\base.py", line 112, in **call** return await self._invoke(prompt, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Anaconda\envs\graphrag\Lib\site-packages\fnllm\base\base.py", line 128, in _invoke return await self._decorated_target(prompt, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Anaconda\envs\graphrag\Lib\site-packages\fnllm\services\json.py", line 71, in invoke return await delegate(prompt, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Anaconda\envs\graphrag\Lib\site-packages\fnllm\services\retryer.py", line 109, in invoke result = await execute_with_retry() ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Anaconda\envs\graphrag\Lib\site-packages\fnllm\services\retryer.py", line 106, in execute_with_retry raise RetriesExhaustedError(name, self._max_retries)
> 
> And my setting is: llm: api_key: Xinference # set this in the generated .env file type: openai_chat # or azure_openai_chat model: glm4-chat model_supports_json: true # recommended if this is available for your model. api_base: http://127.0.0.1:9997/v1
> 
> parallelization: stagger: 0.3
> 
> # num_threads: 50
> async_mode: threaded # or asyncio
> 
> embeddings: async_mode: threaded # or asyncio vector_store: type: lancedb db_uri: 'output\lancedb' container_name: default overwrite: true llm: api_key: Xinference type: openai_embedding # or azure_openai_embedding model: bge-large-zh-v1.5 api_base: http://127.0.0.1:9997/v1 # api_version: 2024-02-15-preview # audience: "https://cognitiveservices.azure.com/.default" # organization: <organization_id> # deployment_name: <azure_model_deployment_name>

Have you completed you web service exactly according to [openai standards](https://platform.openai.com/docs/api-reference/chat)? From the first line of your log file it looks like this script is not getting the correct request response(502).

**Comment by baijumohamed** [comment]
I’m running into the exact same error as mentioned earlier and have tried all suggested solutions without success. I’m using GPT-4-Turbo and text-embedding-ada-002 for embeddings.

Here’s my setup

In .env
GRAPHRAG_API_KEY=Token generated for our firm’s connectivity  
OPEN_AI_BASE_URL=https://myfirms-gateway.dev.com/openai/v1  

In settings.yaml:
api_base: https://myfirms-gateway.dev.com/openai/v1  

The strange part is that no matter what token i use (valid or invalid), I always get the same error - Operation Chat failed.

The stack trace points to fnllm\services\retryer throwing a Retries exhauster error. Can't see any 'POST' in the logs to see which end point its actually hitting.

1. Has anyone successfully connect via their firm's gateway URL ?
2. Why is it trying to hit this fnllm package ? is that a wrapper ?
3. Are there any example use cases for calling graphrag --index in a programmatic way (not the command way) constructing required config objects, llm embedding etc so we can explicitly invoke knowing what is being passed on.

Any help or pointers would be greatly appreciated.

**Comment by lsukharn** [comment]
I got the same error message. I am using Azure OpenAI. Tried to add /v1 to my base url and increased TPM to 140K. Not sure what helped, but I finally got `All workflows completed successfully.`
