### ISSUE TITLE
IO error in lancedb write operation

### ISSUE THREAD

**Issue by pratham16cse** [microsoft/graphrag#295]
Facing an IOError in the lancedb write operation in the `store_entity_semantic_embeddings` call during local search (https://github.com/microsoft/graphrag/blob/main/examples_notebooks/local_search.ipynb). 

I was able to reproduce the error with following code:
```
import lancedb
import pandas as pd
import pyarrow as pa

uri = "data/sample-lancedb"
db = lancedb.connect(uri)
data = [
    {"vector": [3.1, 4.1], "item": "foo", "price": 10.0},
    {"vector": [5.9, 26.5], "item": "bar", "price": 20.0},
]
tbl = db.create_table("my_table", data=data)
```

Is there any standard way to fix this that I might have missed? Any authentication I need to do with lancedb?

**Comment by AyushExel** [comment]
Hello, I'm from LanceDB team. What error are you seeing?

**Comment by pratham16cse** [comment]
Thanks @AyushExel. Attaching the screenshot of the error with the above code.

![image](https://github.com/microsoft/graphrag/assets/47747080/816dec8a-b311-482f-a4ea-f9d52e1692b5)

**Comment by AyushExel** [comment]
the error seems to be related to write permission in the folder. Can you double check that

**Comment by pratham16cse** [comment]
Yes, the error is due to write permission. However, I am getting the same error in other machine as well. I am using Azure VM. Any configuration or settings that I might have missed?

**Comment by pratham16cse** [comment]
In Azure VM, lancedb does not have write permission in the directory `/home/<username>/cloudfiles`, hence the error. By changing the write path to `/home/<username>/localfiles`, the issue is resolved. Similar issue [here](https://github.com/delta-io/delta-rs/issues/1952#issuecomment-2126185538).

Closing the issue for now, will reopen if needed. Thanks.

**Comment by georgeliang0821** [comment]
@pratham16cse How can I change the write path from /home//cloudfiles to /home//localfiles in Azure ML Studio?
