### ISSUE TITLE
cursor disappears on completion of execution

### ISSUE THREAD

**Issue by GaryDean** [microsoft/graphrag#330]
system: ubuntu 22.04

Whenever a graphrag.* module is executed, the terminal cursor is turned off.  Annoying.

```[tasklist]
### Tasks
```

**Comment by jgbradley1** [comment]
I believe this is an artifact of how we’re displaying data frames and progress during the indexing/query process. Our goal is to display to users regular updates.

As an alternative approach, you can run the CLI commands and send them to a background process which would hide all stdout.

Closing this issue for now but we welcome all contributions.
