### ISSUE TITLE
Broken link for Prompt Tuning Guide

### ISSUE THREAD

**Issue by fire** [microsoft/graphrag#333]
> Using GraphRAG with your data out of the box may not yield the best possible results. We strongly recommend to fine-tune your prompts following the [Prompt Tuning Guide](https://microsoft.github.io/graphrag/posts/index/3-prompt_tuning) in our documentation.

https://microsoft.github.io/graphrag/

https://microsoft.github.io/graphrag/posts/index/3-prompt_tuning

**Comment by AlonsoGuevara** [comment]
Thanks for the report

Fixed in #352
