### ISSUE TITLE
Generated graph contains entities that do not appear in the original text

### ISSUE THREAD

**Issue by eyast** [microsoft/graphrag#334]
I have been running the graphrag accelerator (with GPT4-o on AOAI) on the [complete works of Sir Arthur Connan Doyle](https://sherlock-holm.es/ascii/), without modifying the entity configuration.

Observing the retrieved graph using Gephi shows a cluster of interconnected nodes which do not exist in the source text. Each node has a source_id pointing to a text_unit chunk, but when I retrieve those chunks from `create_bsed_text_units.parquet`, they do not contain any mention of these entities.
The entity labels are:
- Iran
- Tehran
- Emad Shargi
- Evin prison
- Siamak Nazari
- There might be more, but these caught my eye

Further search in `cache/entity_extraction` shows these bogus entities returned by GPT. See `'sherlock4/cache/entity_extraction\\chat-00bc8a92b836ff7c6890f16e0d8a3bd5'` for example.
Link to all the files that were stored on Blob: https://www.dropbox.com/scl/fi/nmx5nrdt5w6rx4t7chitp/sherlock_holmes_graphrag.zip?rlkey=tkbakww4cuogsmt8f94rduea9&dl=0

**Comment by jstoneman-ME** [comment]
Interesting! Did you use the Auto Templating https://microsoft.github.io/graphrag/posts/prompt_tuning/overview/ to prompt tune the indexing?

**Comment by eyast** [comment]
No, I have not, but I think I now know where the problem is, and it might be two-fold:
1. The version I have (v0.0.1) has a prompt template defined in `index/graph/extractors/graph/prompts.py` which had few shot examples that included Tehran, Iran, and all those other strange entities.
2. During indexing, few errors appeared on the console (below). I don't know exactly what the source of the problem is, nor where it happened or why. The process continued silently, and I was eager to see a graph built. I don't know if it's related or not, but it seems that in some (unknown?) cases, the few-shot in-context learning examples can be incorrectly marked as graph entities. Potentially, we could adjust the pipeline to add a validation step (maybe, once the LLM extract entities, another steps does a search in the text to make sure it's there)? I would have done that myself and submitted a PR, but I'm afraid I don't have a good command of Datashaper yet.

[logs.json](https://github.com/user-attachments/files/16077742/logs.json)

**Comment by AlonsoGuevara** [comment]
Hi @eyast 
Please use the version from pip and try again.
Also, we recommend running auto templating https://microsoft.github.io/graphrag/posts/prompt_tuning/overview/ this will fine your prompts to your dataset.
