### ISSUE TITLE
There are some questions about application integration

### ISSUE THREAD

**Issue by linfwj** [microsoft/graphrag#337]
1. How do I store graph content in a database instead of a file？
2. Is there an HTTP API available for application integration queries?

**Comment by eyast** [comment]
With regards to the 2nd question, please have a look at the [GraphRAG accelerator](https://github.com/Azure-Samples/graphrag-accelerator/tree/main). The accelerator shows you how to deploy a GraphRAG web application on Azure Kubernetes Services, nginx, Azure API Management (API-M), and few other configurations that make it easily accessible for your users or applications to access GraphRAG through a REST API endpoint.

**Comment by AlonsoGuevara** [comment]
Hi @linfwj 

1. We only support graphml, csv, json and parquet outputs at the time. I would suggest taking a look at how we store the graph in here: [snapshot rows](https://github.com/microsoft/graphrag/blob/a22003c302bf4ffeefec76a09533acaf114ae7bb/graphrag/index/verbs/snapshot_rows.py#L24) Every line of the dataframe is a graph in graphml format, and whever we want to "snapshot" it we call this function with text as the format and graphml as the extension
2. As @eyast suggest, I would direct you to the [Accelerator Solution](https://github.com/Azure-Samples/graphrag-accelerator/tree/main) it deploys everything into a cloud solution.
