### ISSUE TITLE
How to visualize the graph? 

### ISSUE THREAD

**Issue by pandyamarut** [microsoft/graphrag#340]
After embedding the dataset and graph creation, is there anyway currently to visualise the data, as it is shown in the blogpost?

**Comment by Lbaiall** [comment]
same question

**Comment by noworneverev** [comment]
I’m not sure if this is the correct way, but I changed graphml to true in settings.yaml. You can then visualize the graph using a tool like Gephi.

**Comment by jgbradley1** [comment]
@noworneverev  is correct. Setting

```yaml
snapshots:
  graphml: True
```

will lead to graphml files getting generated in the output folder. The graphml format is an open standard supported by several OSS tools. [Gephi](https://gephi.org/) was used to generate many of the knowledge graph images that you may have seen in relation to graphrag.

If there are other formats that the community would prefer, we welcome all contributions.

**Comment by fskpf** [comment]
Another way to visualize the graph is shown in [graph-visualization.ipynb](https://github.com/microsoft/graphrag/blob/main/examples_notebooks/community/yfiles-jupyter-graphs/graph-visualization.ipynb). It embeds an interactive graph visualization of the parquet files and graphrag's result context in the Jupyter notebook.

**Comment by hashirnouman** [comment]
it's now working I set graphml value to True

**Comment by noworneverev** [comment]
Check out [GraphRAG-Visualizer](https://noworneverev.github.io/graphrag-visualizer/)! 

Simply upload your parquet files to visualize your graph data. No need for Neo4j or Jupyter Notebook.

- View your graph in 2D and 3D.
- Display and search parquet file data in tables.
- Focus on specific nodes or relationships with powerful search functionality.
- Process your data locally, ensuring it remains secure and private.

![image](https://github.com/user-attachments/assets/38fe21d7-979d-49f3-ab6c-d1715ce0eccb)

**Comment by mohammadmaso** [comment]
> Check out [GraphRAG-Visualizer](https://noworneverev.github.io/graphrag-visualizer/)!
> 
> Simply upload your parquet files to visualize your graph data. No need for Neo4j or Jupyter Notebook.
> 
> * View your graph in 2D and 3D.
> * Display and search parquet file data in tables.
> * Focus on specific nodes or relationships with powerful search functionality.
> * Process your data locally, ensuring it remains secure and private.
> 
> ![image](https://private-user-images.githubusercontent.com/18380064/356177279-38fe21d7-979d-49f3-ab6c-d1715ce0eccb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzODYxNDYsIm5iZiI6MTcyNTM4NTg0NiwicGF0aCI6Ii8xODM4MDA2NC8zNTYxNzcyNzktMzhmZTIxZDctOTc5ZC00OWYzLWFiNmMtZDE3MTVjZTBlY2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDE3NTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ZmNjZTY2ODg3OTk0NzJjNWIwZWQ4MTgzZTBlYjBkMWQ1YTYyZDIxYWM2ZmQ5OWIyNGZlYWRmN2RiZjQyZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u7soUq2DNkfo69imwY3mRgC8m-Bb2H3C47l7Aor0YVE)

This is awesome!!!! Thanks

**Comment by Shavvimal** [comment]
You could also adapt the `graphrag.index.graph.visualization.compute_umap_positions.visualize_embedding` method. To use UMAP layouts for visualization, we need to enable it in the `settings.yaml`  file first (umap.enabled) to emit the UMAP `x` and `y` coordinates for each node in a 2D space.

Ive written a scrappy [Gist](https://gist.github.com/Shavvimal/b6e6c90787d8d081bc23161284ecbcd7) to do this, but you can create some pretty nifty graphs with these UMAP representations to visualize the graph in a 2D space / understand the relationships between the nodes in the graph. You could, of course, also visualise using tools like Gephi or other graph visualization software using the UMAP coordinates

![image](https://github.com/user-attachments/assets/97980fb9-9acf-4591-8a43-4c1e846fddd8)
