### ISSUE TITLE
How to integrate the function into my rag system

### ISSUE THREAD

**Issue by Lbaiall** [microsoft/graphrag#342]
That's pretty familiar function with the recently repo which name “Hipporag”
But one more thing i still want to know is ....
Dose it the can integrate the function into my rag system

**Comment by jgbradley1** [comment]
Can you clarify what your question is? We provide some notebook examples [here](https://microsoft.github.io/graphrag/posts/query/notebooks/overview) that demonstrates how to programmatically query a graphrag index. You could take that code as a starting point and transform it into a function that integrates into your system.

**Comment by Lbaiall** [comment]
@jgbradley1 
i meaning that where is your soure code ,and which module than your integrate ,i need to know the structure it is ，than.... i can useing it appropriate in my Chat system

**Comment by misi0202** [comment]
@

> @jgbradley1 i meaning that where is your soure code ,and which module than your integrate ,i need to know the structure it is ，than.... i can useing it appropriate in my Chat system

You can find source code in the py package(graphrag), It clear in every step,plz ensure you have installed it XD.

**Comment by Lbaiall** [comment]
@misi0202  appreciate it ！
