### ISSUE TITLE
Unknown workflow: entity_extraction when running graphrag\examples\entity_extraction\with_graph_intelligence\run.py

### ISSUE THREAD

**Issue by thomasjlittle** [microsoft/graphrag#353]
Hi, sorry if I have overlooked a simple solution to this, but I am running into the following error when trying to run the example scripts for entity extraction with graph intelligence. 

Example file: entity_extraction when running graphrag\examples\entity_extraction\with_graph_intelligence\run.py

Exception has occurred: UnknownWorkflowError
Unknown workflow: entity_extraction
  File "C:\Users\user\dev\MSGraphRag\graphrag\examples\entity_extraction\with_graph_intelligence\run.py", line 95, in run_python
    async for table in run_pipeline(dataset=dataset, workflows=workflows):
  File "C:\Users\user\dev\MSGraphRag\graphrag\examples\entity_extraction\with_graph_intelligence\run.py", line 107, in <module>
    asyncio.run(run_python())
graphrag.index.errors.UnknownWorkflowError: Unknown workflow: entity_extraction

it looks like the 'entity_extraction' workflow is not in the default_workflows.py file or in the workflows.v1 folder either

**Comment by martinpenchev** [comment]
I guess they changed the names. I got it working like this:

```python
workflows: list[PipelineWorkflowReference] = [
    PipelineWorkflowReference(
        name="create_base_extracted_entities",
        config={
            "entity_extract": {
                "strategy": {
                    "type": "nltk",
                }
            }
        },
    ),
    PipelineWorkflowReference(
        name="create_base_entity_graph",
        config={
            "cluster_graph": {"strategy": {"type": "leiden"}},
            "embed_graph": {
                "strategy": {
                    "type": "node2vec",
                    "num_walks": 10,
                    "walk_length": 40,
                    "window_size": 2,
                    "iterations": 3,
                    "random_seed": 597832,
                }
            },
            "layout_graph": {
                "strategy": {
                    "type": "umap",
                },
            },
        },
    ),
]
```

**Comment by TudorAndrei** [comment]
It also doesn't work for me. Even with martinpenchev's code snippet.

**Comment by vinayybhore** [comment]
me too!
<img width="1291" alt="image" src="https://github.com/user-attachments/assets/897d017a-9c10-410a-8881-fcd01f40e5ce">

**Comment by xinzheng99** [comment]
> I guess they changed the names. I got it working like this:
> 
> ```python
> workflows: list[PipelineWorkflowReference] = [
>     PipelineWorkflowReference(
>         name="create_base_extracted_entities",
>         config={
>             "entity_extract": {
>                 "strategy": {
>                     "type": "nltk",
>                 }
>             }
>         },
>     ),
>     PipelineWorkflowReference(
>         name="create_base_entity_graph",
>         config={
>             "cluster_graph": {"strategy": {"type": "leiden"}},
>             "embed_graph": {
>                 "strategy": {
>                     "type": "node2vec",
>                     "num_walks": 10,
>                     "walk_length": 40,
>                     "window_size": 2,
>                     "iterations": 3,
>                     "random_seed": 597832,
>                 }
>             },
>             "layout_graph": {
>                 "strategy": {
>                     "type": "umap",
>                 },
>             },
>         },
>     ),
> ]
> ```

If you have a suitable CSV file could you provide a copy? Because I don't find the input csv file for that program in the code. Thank you very much. @martinpenchev
