### ISSUE TITLE
Wrong link in get_started

### ISSUE THREAD

**Issue by KannbaraQRS** [microsoft/graphrag#355]
> ## Requirements
>
>[Python 3.10-3.12](https://www.python.org/downloads/)
>
>To get started with the GraphRAG system, you have a few options:
>
>👉 [Use the GraphRAG Accelerator solution](https://github.com/Azure-Samples/graphrag-accelerator) <br/>
>👉 [Install from pypi](https://pypi.org/project/graphrag/). <br/>
>👉 [Use it from source](/posts/developing)<br/>

In [get_started page](https://github.com/microsoft/graphrag/blob/main/docsite/posts/get_started.md) found a wrong link for **Use it from source**:
https://github.com/microsoft/graphrag/blob/main/posts/developing
I think it should be 
https://github.com/microsoft/graphrag/blob/main/docsite/posts/developing.md

**Comment by AlonsoGuevara** [comment]
Hi @KannbaraQRS 
Thanks for your interest in contributing with issues to our repo, we appreciate it.

In this case, the link is fine, both page host the same content, so this won't be a bug.

**Comment by albaNnaksqr** [comment]
Hi @AlonsoGuevara
 I think you mean this link `https://microsoft.github.io/graphrag/posts/developing/`
but the link you provided in get_started(`https://github.com/microsoft/graphrag/blob/main/posts/developing`) will return a **404 Page Not Found** . 
Sorry if I got it wrong.
