### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by johntangxia** [microsoft/graphrag#402]
after run: 
python -m graphrag.index --root ./ragtest
error:   
File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by johntangxia** [comment]
who met this issue, pls give  a hand

**Comment by vsecoder** [comment]
Try another encoding? Set utf-8:
![image](https://github.com/microsoft/graphrag/assets/60792943/1711b4e4-32a5-445c-96c8-99b615e4189d)

**Comment by z4656207** [comment]
> Try another encoding? Set utf-8:尝试其他编码？设置 utf-8： ![image](https://private-user-images.githubusercontent.com/60792943/346319170-1711b4e4-32a5-445c-96c8-99b615e4189d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNTI3NDMsIm5iZiI6MTcyMDM1MjQ0MywicGF0aCI6Ii82MDc5Mjk0My8zNDYzMTkxNzAtMTcxMWI0ZTQtMzJhNS00NDVjLTk2YzgtOTliNjE1ZTQxODlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDExNDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlYzVjYzUxYWFjN2E4Yzc2OGM3MzFiMDhiM2MwM2ZlNjVjNWVlNWFjZTJjMGY5M2VmYjM0NDA2MjRiMWQ3NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mf5IcRPliMrBJ3s9ySQE2Rj0MR-VCawT8I-YqU1eX5U)

modify the update file?

**Comment by johntangxia** [comment]
> Try another encoding? Set utf-8: ![image](https://private-user-images.githubusercontent.com/60792943/346319170-1711b4e4-32a5-445c-96c8-99b615e4189d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNjEyMjQsIm5iZiI6MTcyMDM2MDkyNCwicGF0aCI6Ii82MDc5Mjk0My8zNDYzMTkxNzAtMTcxMWI0ZTQtMzJhNS00NDVjLTk2YzgtOTliNjE1ZTQxODlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE0MDIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MWQxODFjZTg3MjJmNzEyMzJhYmUxOWIxOTg4NDY1OWM0MDcyMzRlY2NmYWUxZDYyYjVhZGZmOTcwYTdmOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vd4Ifj_fwjTU_ibAIQYxVvActAJwJC6h3X0hwZNsHBA)

**Comment by johntangxia** [comment]
> Try another encoding? Set utf-8: ![image](https://private-user-images.githubusercontent.com/60792943/346319170-1711b4e4-32a5-445c-96c8-99b615e4189d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNjM2NTEsIm5iZiI6MTcyMDM2MzM1MSwicGF0aCI6Ii82MDc5Mjk0My8zNDYzMTkxNzAtMTcxMWI0ZTQtMzJhNS00NDVjLTk2YzgtOTliNjE1ZTQxODlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE0NDIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ODE1OGE0NDI0OGIxZmI5NjhkM2YwNzZjMjRlZGM1YmEwMjc5ODhlNzVjYjY0YjhjODdhMDNkNWZlMWRhNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cVa1Oz3DHoiIaqq_m49ua2Vmw6SU3uggYscTiKdzQqc)

where to modify this config? thx

**Comment by caifanfan** [comment]
解决了么？我没看明白
