### ISSUE TITLE
Failed with "from graphrag import index"

### ISSUE THREAD

**Issue by cheepon** [microsoft/graphrag#413]
I got `illegal instruction` error when "from graphrag import index" which from "import lancedb as lancedb".
I found the issue: [https://github.com/lancedb/lance/issues/2195](url)

Is "lancedb" a necessary one for graphrag? It may cause graphrag confront with this issue too.

**Comment by jgbradley1** [comment]
At this time, lancedb is a necessary package. `graphrag` uses lancedb as the preferred choice for a local vector database at query time. There are a couple of issues/PR’s open looking at using other vector DB’s. When those have been vetted, we can look at marking lancedb as an extra’s package or provide a way to skip lancedb in favor of other options.

Based on the issue you linked, it sounds like you may be using an intel CPU that is > 10 years old. Even if the lancedb requirement is removed, consider the possibility that other vector db options may not work well on your system either.

**Comment by sam-bercovici** [comment]
Just did quick sanity. 
Both qdrant and milvus run on my 10 years old intel CPU - "Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz"
