### ISSUE TITLE
Documentation Request: How to export Graph visualization

### ISSUE THREAD

**Issue by emerzon** [microsoft/graphrag#415]
I would like to visually inspect the knowledge graph of my data, just like in the example shown at https://microsoft.github.io/graphrag/ `Figure 1: An LLM-generated knowledge graph built using GPT-4 Turbo.`

How to generate that?

**Comment by AlonsoGuevara** [comment]
Hi!

If you set this [config line](https://github.com/microsoft/graphrag/blob/a22003c302bf4ffeefec76a09533acaf114ae7bb/graphrag/index/init_content.py#L134) in your settings.yaml you'll get the graphml files as part of your output.

**Comment by fskpf** [comment]
Another way to visualize the graph is shown in [graph-visualization.ipynb](https://github.com/microsoft/graphrag/blob/main/examples_notebooks/community/yfiles-jupyter-graphs/graph-visualization.ipynb). It embeds an interactive graph visualization of the parquet files and graphrag's result context in the Jupyter notebook. This also lets you explore the graph to [yEd Live](https://www.yworks.com/yed-live/) with which you can easily create image exports.

**Comment by noworneverev** [comment]
Check out [GraphRAG-Visualizer](https://noworneverev.github.io/graphrag-visualizer/)! 

Simply upload your parquet files to visualize your graph data. No need for Neo4j or Jupyter Notebook.

- View your graph in 2D and 3D.
- Display and search parquet file data in tables.
- Focus on specific nodes or relationships with powerful search functionality.
- Process your data locally, ensuring it remains secure and private.

![image](https://github.com/user-attachments/assets/38fe21d7-979d-49f3-ab6c-d1715ce0eccb)
