### ISSUE TITLE
How can we create RAG dynamicly?

### ISSUE THREAD

**Issue by SP4595** [microsoft/graphrag#429]
I am currently facing a challenge with adding new text to RAG. My current approach involves reinitializing the entire RAG, which is slow.

Please provide guidance or suggestions on efficiently adding new text to RAG without requiring complete reinitialization.

**Comment by hemangjoshi37a** [comment]
> I am currently facing a challenge with adding new text to RAG. My current approach involves reinitializing the entire RAG, which is slow.
> 
> Please provide guidance or suggestions on efficiently adding new text to RAG without requiring complete reinitialization.

I have same requirement , I want to use this for coding in which everytime i make small changes I have to reindex whole codebase which is very slow . if you find anything please let me know.

**Comment by SP4595** [comment]
> hi . are you using it with openai ? what is the indexing cost for this ?

Sorry, I use the Ollama & llama3-8b. But some YouTubers said openai api will cost a lot.

**Comment by kdawgwilk** [comment]
If you just add a new file to the `input` folder it will incrementally index

**Comment by hemangjoshi37a** [comment]
If anyone has it running on ollama please let me know how to set it up.

**Comment by Janice0721** [comment]
If you know how to dynamically add text without generating a full index again, please let me know. Thank you

**Comment by natoverse** [comment]
If you add new content to the input and _do _not__  change your indexing parameters, you should get the benefit of the cache on many of the requests. Changing parameters changes the cache key though, causing a complete reindex.

There are some steps in the pipeline that will re-run due to changed inputs any time you add content.

**Comment by hemangjoshi37a** [comment]
If anyone has achieved or can suggest for this . In this we want to continuously index the updated code base in the HippoRAG index and query on the updated index and then make code changes and continuously do so. Here consider that we want to do this offline with ollama type models only and dont want to use OpenAI or Claude .

If anyone can suggest how can i do this ?

**Comment by natoverse** [comment]
Consolidating index update requests with #741
