### ISSUE TITLE
How to store data in neo4j?

### ISSUE THREAD

**Issue by crazyyanchao** [microsoft/graphrag#433]

**Comment by jexp** [comment]
see: https://github.com/microsoft/graphrag/issues/418#issuecomment-2224246436

**Comment by jexp** [comment]
https://github.com/microsoft/graphrag/pull/544

**Comment by natoverse** [comment]
Great writeup here: https://towardsdatascience.com/integrating-microsoft-graphrag-into-neo4j-e0d4fa00714c
