### ISSUE TITLE
Support graph visualization

### ISSUE THREAD

**Issue by kdawgwilk** [microsoft/graphrag#446]
The published paper has a few example pictures showcasing the graph in a visualized way and i think it would be very valuable to be able to get a similar output from the indexed outputs

**Comment by noworneverev** [comment]
It's already supported, please refer to #340.

**Comment by noworneverev** [comment]
> The published paper has a few example pictures showcasing the graph in a visualized way and i think it would be very valuable to be able to get a similar output from the indexed outputs

It's already supported, please refer to https://github.com/microsoft/graphrag/issues/340.

**Comment by AlonsoGuevara** [comment]
Hi @kdawgwilk 
Please turn this flag on in settings:
```yaml
snapshots:
  graphml: True
```

This will generate a bunch of gramphl outputs. Look at summarized_graph.graphml, this is the one you would be aiming to load in Gephi.
Once loaded into Gephi you can play with the different community and clustering algorithms to obtain your desired visualization.
In our case, we run Leiden and Average Degree. Then, for graph layout we do OpenOrd and ForceAtlas2.

I'm planning on a adding a detailed guide for this on the docs so people can recreate the graphs.

**Comment by fskpf** [comment]
@AlonsoGuevara What do you think about adding some documentation / samples or even API integration to display the graph as an interactive jupyter cell?
For example, as commented [here](https://github.com/microsoft/graphrag/issues/418#issuecomment-2220349505).

**Comment by fskpf** [comment]
Although not the same visualization as in the blogpost, [graph-visualization.ipynb](https://github.com/microsoft/graphrag/blob/main/examples_notebooks/community/yfiles-jupyter-graphs/graph-visualization.ipynb) shows how to create an interactive graph visualization of the parquet files and graphrag's result context in a Jupyter notebook.

**Comment by noworneverev** [comment]
Check out [GraphRAG-Visualizer](https://noworneverev.github.io/graphrag-visualizer/)! 

Simply upload your parquet files to visualize your graph data. No need for Neo4j or Jupyter Notebook.

- View your graph in 2D and 3D.
- Display and search parquet file data in tables.
- Focus on specific nodes or relationships with powerful search functionality.
- Process your data locally, ensuring it remains secure and private.

![image](https://github.com/user-attachments/assets/38fe21d7-979d-49f3-ab6c-d1715ce0eccb)

**Comment by alopez5566** [comment]
I'm using the graph rag accelerator API, any way to get the parquet files? or any tool or script to convert graphml to parquet ?. Thank you
