### ISSUE TITLE
Parallel indexing support?

### ISSUE THREAD

**Issue by K2559** [microsoft/graphrag#453]
### Describe the issue

A single api or model can provide just around 100 token/sec max, still too slow if indexing a lot of files. Is it possible we use multiple api to have parallel indexing to speed up the processing?

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by eyast** [comment]
Hi! Yes, parallelization is available. You will find the settings in your `settings.yaml` file, where you can set the `parallelization.num_threads` settings to define how many processes you want to run in parallel.

**Comment by jgbradley1** [comment]
@K2559 we do not currently support the use of multiple API endpoints at this time. I assume you are referring to a load balanced setup similar to the diagrams [here](https://github.com/Azure-Samples/openai-apim-lb) except without the API Management component? This scenario has not been tested but if you do have a load-balanced setup depicted in those diagrams, I cannot think of any restriction in our codebase that would prevent the use of multiple OpenAI models.

**Comment by aimanyounises1** [comment]
hi @jgbradley1 ,

How is that can be done pls? this would help accelerating the indexing process

**Comment by disperaller** [comment]
> Hi! Yes, parallelization is available. You will find the settings in your `settings.yaml` file, where you can set the `parallelization.num_threads` settings to define how many processes you want to run in parallel.

I changed the num_threads in the settings.yaml to 20, but the process still seems pretty slow:
![image](https://github.com/user-attachments/assets/7b4f46d8-243b-478e-b3b1-695ddf579da4)

Is there anyway to speed up the indexing process?
