### ISSUE TITLE
[Issue]: graphrag.index module not found 

### ISSUE THREAD

**Issue by satyaprakash1729** [microsoft/graphrag#465]
### Describe the issue

I'm following the documentation specified at https://microsoft.github.io/graphrag/posts/get_started/
I'm getting below error when I try to run `python -m graphrag.index --init --root ./ragtest`

_/home/<user>/.pyenv/versions/3.9.14/bin/python: No module named graphrag.index_

I'm using Ubuntu

### Additional Information

- GraphRAG Version: 0.0.0
- Operating System: Ubuntu 20.04.6 LTS (Focal Fossa)
- Python Version: 3.9.14
- Related Issues:

**Comment by AlonsoGuevara** [comment]
Hi @satyaprakash1729 
To use GraphRAG the minimmal Python version is 3.10.
Please upgrade your python version and retry :)

**Comment by minfawang** [comment]
I'm using 3.10.13 and getting the same error:

```
$ python -m graphrag.index --init --root ./ragtest
/$ROOT/.venv/bin/python: No module named graphrag.index
```

**Comment by minfawang** [comment]
Ok found the workaround. When I'm using `pipenv`, somehow by default it is trying to install `graphrag@0.0.0`, which is empty. I had to fix the graphrag version:

```shell
# Wrong: will install 0.0.0
pipenv install graphrag

# Ok
pipenv install graphrag==0.1.1
```

**Comment by AlonsoGuevara** [comment]
Interesting... I'll double check pypi! Thanks for updating!

**Comment by zongzi531** [comment]
I'm still `No module named graphrag.index` , Anyone knows how to fix this ?

Versions:
```
Python 3.12.4
graphrag 0.2.0
```

**Comment by zongzi531** [comment]
> I'm still `No module named graphrag.index` , Anyone knows how to fix this ?
> 
> Versions:
> 
> ```
> Python 3.12.4
> graphrag 0.2.0
> ```

I found the problem. I use `conda` envs , but I used global `pip` installed graphrag, so `python -m pip install <package>` can solved.
