### ISSUE TITLE
[Bug]: <title>Error executing verb "window" in create_final_community_reports: 'community'

### ISSUE THREAD

**Issue by Iceice2024** [microsoft/graphrag#476]
### Describe the bug

15:36:46,423 datashaper.workflow.workflow ERROR Error executing verb "window" in create_final_community_reports: 'community'
Traceback (most recent call last):
  File "C:\���\mygraphrag\venv\Lib\site-packages\datashaper\workflow\workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\���\mygraphrag\venv\Lib\site-packages\datashaper\engine\verbs\window.py", line 73, in window
    window = __window_function_map[window_operation](input_table[column])
                                                     ~~~~~~~~~~~^^^^^^^^
  File "C:\���\mygraphrag\venv\Lib\site-packages\pandas\core\frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\���\mygraphrag\venv\Lib\site-packages\pandas\core\indexes\range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'community'



### Steps to reproduce

_No response_

### Expected Behavior

_No response_

### GraphRAG Config Used

_No response_

### Logs and screenshots

_No response_

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by shreyn07** [comment]
Even I got the same errror

**Comment by shreyn07** [comment]
How did you solved above error

**Comment by vanwor** [comment]
same error

**Comment by sadimoodi** [comment]
same error here

**Comment by shreyn07** [comment]
In settings.yml change comment model supports json line,

It works for me

**Comment by sadimoodi** [comment]
> In settings.yml change comment model supports json line,
> 
> It works for me

change it to what value? true or false? false at lest doesnt work for me

**Comment by xxll88** [comment]
comment it , delete cache and reindex ,everything is ok

**Comment by HugoWang232608** [comment]
> comment it , delete cache and reindex ,everything is ok

It works for me, thanks.

**Comment by Malowking** [comment]
> comment it , delete cache and reindex ,everything is ok

Comment which line of code?

**Comment by HugoWang232608** [comment]
> > comment it , delete cache and reindex ,everything is ok
> 
> Comment which line of code?
```yaml
model_supports_json: true
```
