### ISSUE TITLE
[Bug]: cannot set llm params top_p and temperature when query

### ISSUE THREAD

**Issue by liseri** [microsoft/graphrag#479]
### Describe the bug

custom set llm params tops and temperature is invalid when query

### Steps to reproduce

1. custom modify llm  top_p and temperature params in settings.yaml
2. run global or local query

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by yuguosen** [comment]
they are `llm_temperature` and  `llm_top_p`,source code:
`global_search_model = GlobalSearchConfig(
                temperature=reader.float("llm_temperature")
                or defs.GLOBAL_SEARCH_LLM_TEMPERATURE,
                top_p=reader.float("llm_top_p") or defs.GLOBAL_SEARCH_LLM_TOP_P,
                n=reader.int("llm_n") or defs.GLOBAL_SEARCH_LLM_N,
                max_tokens=reader.int(Fragment.max_tokens)
                or defs.GLOBAL_SEARCH_MAX_TOKENS,
                data_max_tokens=reader.int("data_max_tokens")
                or defs.GLOBAL_SEARCH_DATA_MAX_TOKENS,
                map_max_tokens=reader.int("map_max_tokens")
                or defs.GLOBAL_SEARCH_MAP_MAX_TOKENS,
                reduce_max_tokens=reader.int("reduce_max_tokens")
                or defs.GLOBAL_SEARCH_REDUCE_MAX_TOKENS,
                concurrency=reader.int("concurrency") or defs.GLOBAL_SEARCH_CONCURRENCY,
            )`
