### ISSUE TITLE
create_final_covariates.parquet not generated[Issue]: <title> 

### ISSUE THREAD

**Issue by win4r** [microsoft/graphrag#483]
### Describe the issue

create_final_covariates.parquet not generated

### Steps to reproduce

create_final_covariates.parquet not generated

### GraphRAG Config Used

create_final_covariates.parquet not generated

### Logs and screenshots

create_final_covariates.parquet not generated

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by AlonsoGuevara** [comment]
Hi @win4r
Can you please provide more details? If you can share your settings file I can troubleshoot

**Comment by AlonsoGuevara** [comment]
Duplicate of #498
Resolving
