### ISSUE TITLE
[Issue]: tokens_per_minute setting not working as expected 

### ISSUE THREAD

**Issue by nikhilmaddirala** [microsoft/graphrag#490]
### Describe the issue

Indexing is exceeding my rate limit of 60,000 tokens per minute

### Steps to reproduce

Settings:
```
tokens_per_minute: 50000 # set a leaky bucket throttle
requests_per_minute: 500 # set a leaky bucket throttle

```

Run:
```
python -m graphrag.index --root .
```

### GraphRAG Config Used

[settings.yaml.txt](https://github.com/user-attachments/files/16164781/settings.yaml.txt)

### Logs and screenshots

[logs.json](https://github.com/user-attachments/files/16164762/logs.json)

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by AlonsoGuevara** [comment]
Hi @nikhilmaddirala 
Thanks for the report. We have fixed this issue, so if you use latest main this shall be fixed already.
If you're using pip, I'm looking fwd to a new version release this week.

**Comment by nikhilmaddirala** [comment]
Thanks @AlonsoGuevara — I'm using pip [following the instructions here](https://microsoft.github.io/graphrag/posts/get_started/). Looking fwd to the new release!

**Comment by jgbradley1** [comment]
Closing this issue for now since there is a fix. Please try the new version when we release (or run `poetry build` in the root directory of this repo and install the wheel) and open a new issue if the problem still exist.

**Comment by nikhilmaddirala** [comment]
> Closing this issue for now since there is a fix. Please try the new version when we release (or run `poetry build` in the root directory of this repo and install the wheel) and open a new issue if the problem still exist.

Hi, is there any ETA on the new version with the fix? [Latest release](https://pypi.org/project/graphrag/#history) is not yet updated it seems. Thank you!
