### ISSUE TITLE
[Issue]: <title>  create_final_entities error when i use ollama embedding model

### ISSUE THREAD

**Issue by sysullf** [microsoft/graphrag#504]
### Describe the issue

In order to switch the LLM and embedding modules in Graphrag to the local version, I deployed the ollama service and then configured the Graphrag configuration file according to the requirements https://github.com/TheAiSingularity/graphrag-local-ollama Make modifications, and finally an error occurs in the 'creat_final_dentities' step.
After reading the source code, it was found that Graphrag relies on OpenAI's Python API, which does not support the embedding of ollama.
Do you have any plans to support ollama as a model for LLM and embedding in the future?
thank you.

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by AlonsoGuevara** [comment]
Hi! We are centralizing other LLM discussions in these threads:
Other LLM/Api bases: #339,
Ollama: #345
Local embeddings: #370 

Kindly appreciate if you can bring your question to those threads for community support.
I'll resolve this issue so we can keep the focus on those threads.
