### ISSUE TITLE
I encountered an error while testing the example microsoft/graphrag/examples/entity_extraction: graphrag.index.errors.UnknownWorkflowError: Unknown workflow: entity_extraction.

### ISSUE THREAD

**Issue by hulonghua-devin** [microsoft/graphrag#506]
### Describe the bug

I encountered an error while testing the example microsoft/graphrag/examples/entity_extraction: graphrag.index.errors.UnknownWorkflowError: Unknown workflow: entity_extraction.

### Steps to reproduce

I ran the following command: PYTHONPATH="$(pwd)" python examples/entity_extraction/with_graph_intelligence/run.py
![image](https://github.com/microsoft/graphrag/assets/127592578/e36a620d-3024-4ff0-8f8b-800a9de7b025)
However, when I tested /microsoft/graphrag/examples/custom_set_of_available_workflows, it passed. But when I changed my_workflow to entity_extraction in the code, it failed. What could be the reason? Is it a version issue with graphrag? The version is 0.1.1.
![1720691303786](https://github.com/microsoft/graphrag/assets/127592578/87bc1538-4a2b-41d4-ac16-58679710a7d1)

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by albaNnaksqr** [comment]
maybe you should follow the annotation:  `# should match the name of the workflow in the custom_workflows dict above` and go to `custom_workflow_definitions.py` to change the name in `custiom_workflows` to see if it works.

**Comment by akarim23131** [comment]
I have got the same error message. I am testing an examples of entity extraction.  testing the example microsoft/graphrag/examples/entity_extraction: The unknown workflow error. 
![Image](https://github.com/user-attachments/assets/509e5e7f-ac52-46e7-b4ef-4c96b209bad3)
 Has anyone solved this error.
