### ISSUE TITLE
[Feature Request]: Add out-of-the-box support for HuggingFace API models

### ISSUE THREAD

**Issue by rincon-santi** [microsoft/graphrag#516]
### Is your feature request related to a problem? Please describe.

Right now, only openAI and Azure models are supported out-of-the-box, add support for HF API

### Describe the solution you'd like

Add a huggingface folder in graphrag/llm

**Comment by natoverse** [comment]
Consolidating alternate model issues here: https://github.com/microsoft/graphrag/issues/657
