### ISSUE TITLE
[Issue]: The Default Prompt `GRAPH_EXTRACTION_PROMPT` have some formatting issues

### ISSUE THREAD

**Issue by zhangzhuoBYS** [microsoft/graphrag#519]
### Describe the issue

In `graphrag/index/graph/extractors/graph/prompts.py`, GRAPH_EXTRACTION_PROMPT miss closeing bracket in line 15.

This is fine for large LLM, but it might have an impact on smaller one.

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by dworthen** [comment]
Resolved by #781
