### ISSUE TITLE
如何切换大模型？没看到具体的入口

### ISSUE THREAD

**Issue by PeterXiaTian** [microsoft/graphrag#523]
### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by win4r** [comment]
看这个视频  https://youtu.be/XiLEZzm7yCk

**Comment by jgbradley1** [comment]
Please use GitHub issues to post bugs/feature request. We would love to continue engagement with the open source community over in GitHub Discussions at the top of this page.
