### ISSUE TITLE
[Feature Request]: `milvus` vector storage for indexing and storing graphrag.

### ISSUE THREAD

**Issue by hemangjoshi37a** [microsoft/graphrag#526]
### Is your feature request related to a problem? Please describe.

milvus is very fast and efficient so i want to use it for vector storage for this.

### Describe the solution you'd like

milvus is very fast and efficient so i want to use it for vector storage for this.

**Comment by AlonsoGuevara** [comment]
Hi @hemangjoshi37a 
This is already tracked in #376
We will be merging this soon as part of the community maintained plugins.

**Comment by hemangjoshi37a** [comment]
Ok thanks for #376 PR. 👍
