### ISSUE TITLE
[Issue]: Why do so many nodes have empty community

### ISSUE THREAD

**Issue by tomasonjo** [microsoft/graphrag#529]
### Describe the issue

I was inspecting the example dataset from operation dulge... For some reason most of nodes have no communities. I find it even weirder that nodes that have community on the first level don't necessarily have a community on the second level

### Steps to reproduce

nodes_df = pd.read_parquet('create_final_nodes.parquet')
nodes_df.community.value_counts()
community
1    14
2     9
4     9
0     6
5     5
3     3

There is 217 nodes in total

**Comment by j2whiting** [comment]
It's possible that these are singleton entities that have no relationships. Are those nodes connected to any other nodes in your data?

**Comment by tomasonjo** [comment]
I guess you are right, but then the question is why so little relationships
