### ISSUE TITLE
[Feature Request]: Continue from (or repeat) the last workflow step that failed

### ISSUE THREAD

**Issue by namp** [microsoft/graphrag#531]
### Is your feature request related to a problem? Please describe.

⠇ GraphRAG Indexer
├── Loading Input (InputFileType.text) - 4 files loaded (1 filtered) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00
├── create_base_text_units
├── create_base_extracted_entities
├── create_summarized_entities
├── create_base_entity_graph
└── create_final_entities
❌ Errors occurred during the pipeline run, see logs for more details.

Looking at the log file at ...output//${timestamp}/reports/indexing-engine.log I see the following error:

.../envs/graphrag/lib/python3.11/site-packages/openai/resources/embeddings.py", line 215, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
...

...envs/graphrag/lib/python3.11/site-packages/openai/_base_client.py", line 1577, in _request
    raise APITimeoutError(request=request) from err
openai.APITimeoutError: Request timed out.
19:57:08,567 graphrag.index.reporting.file_workflow_callbacks INFO Error running pipeline! details=None

which means that the workflow failed just because of a (probably) temporary connection error with the embeddings server. 

My question is: 

Is it possible to try again just the failed (last) step, or - in general -  how is it possible to continue from a failed step in the workflow (given that all the previous ones have succeeded) without having to run the whole process from the beginning?

**Comment by AlonsoGuevara** [comment]
Hi @namp
This is supported, it is the --resume flag.

Say for example, you ran this command
```bash
python -m graphrag.index --root my/workspace
```
It failed at a given step, but created a folder named `20240701-223210` (this name will be different for each run). To continue execution from the last successful step, just run this:
```bash
python -m graphrag.index --root my/workspace --resume 20240701-223210
```
Hope this helps :)
Please reopen if needed

**Comment by biandan** [comment]
still not work for me 
#python -m graphrag.index --root ./ragtest --resume 20240715-003521
🚀 Reading settings from ragtest/settings.yaml
/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
❌ create_final_entities
None
⠹ GraphRAG Indexer
├── Loading Input (text) - 1 files loaded (0 filtered) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00
└── create_final_entities
❌ Errors occurred during the pipeline run, see logs for more details.

**Comment by namp** [comment]
It worked for me. Thanks @AlonsoGuevara!
 
@biandan, you should always check the indexing-engine.log in the latest reports directory to see what the error is about and then resume accordingly

**Comment by shawn-maxiao** [comment]
> Hi [@namp](https://github.com/namp) This is supported, it is the --resume flag.
> 
> Say for example, you ran this command
> 
> python -m graphrag.index --root my/workspace
> It failed at a given step, but created a folder named `20240701-223210` (this name will be different for each run). To continue execution from the last successful step, just run this:
> 
> python -m graphrag.index --root my/workspace --resume 20240701-223210
> Hope this helps :) Please reopen if needed


where could I find the resume parameter 20240701-223210 , I use graphrag v1.2.0
