### ISSUE TITLE
[Issue]: <ValueError: No text files found in input  > 

### ISSUE THREAD

**Issue by SeanFeng91** [microsoft/graphrag#563]
### can not load the txt correctly. need help

I have an right .txt file in the input, but it filtered, why?

File "C:\Users\maoxi\github\miniconda3\envs\finance_bot\Lib\site-packages\graphrag\index\run.py", line 144, in run_pipeline_with_config            
    dataset = dataset if dataset is not None else await _create_input(config.input)                                                                  
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                  
  File "C:\Users\maoxi\github\miniconda3\envs\finance_bot\Lib\site-packages\graphrag\index\run.py", line 133, in _create_input                       
    return await load_input(config, progress_reporter, root_dir)                                                                                     
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                     
  File "C:\Users\maoxi\github\miniconda3\envs\finance_bot\Lib\site-packages\graphrag\index\input\load_input.py", line 81, in load_input
    results = await loader(config, progress, storage)                                                                                                
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                
  File "C:\Users\maoxi\github\miniconda3\envs\finance_bot\Lib\site-packages\graphrag\index\input\text.py", line 52, in load                          
    raise ValueError(msg)                                                                                                                            
ValueError: No text files found in input                                                                                                             
⠙ GraphRAG Indexer
└── Loading Input (InputFileType.text) - 0 files loaded (2 filtered) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by SeanFeng91** [comment]
is this related to which model I use?

**Comment by rushizirpe** [comment]
Make sure to create input folder in the project directory and store .txt input files in input.

Worked on notebook:
```
!pip install graphrag

!mkdir -p ./ragtest/input

!curl https://www.gutenberg.org/cache/epub/24022/pg24022.txt > ./ragtest/input/book.txt

!python -m graphrag.index --init --root ./ragtest

!python -m graphrag.index --root ./ragtest
```

**Comment by Friman04** [comment]
same
