### ISSUE TITLE
🔥我为GraphRAG实现了Open WebUI的接入

### ISSUE THREAD

**Issue by win4r** [microsoft/graphrag#566]
### Describe the issue

这是项目代码 https://github.com/win4r/GraphRAG4OpenWebUI
这是视频演示 https://youtu.be/z4Si6O5NQ4c

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by AlonsoGuevara** [comment]
Thanks for your contribution :)
Leaving this open so people can follow your approach, and labeling this as a Community Suport Thread.

**Comment by natoverse** [comment]
Linked in discussion https://github.com/microsoft/graphrag/discussions/697
