### ISSUE TITLE
🔥我为GraphRAG加入了ollama的支持

### ISSUE THREAD

**Issue by win4r** [microsoft/graphrag#577]
### Describe the issue

https://github.com/win4r/GraphRAG4OpenWebUI

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by KylinMountain** [comment]
Abuse of issues, please close.

PS: 你这纯割中国人韭菜, shame on you.

**Comment by win4r** [comment]
> Abuse of issues, please close.
> 
> PS: 你这纯割中国人韭菜, shame on you.

怎么割韭菜了？代码也分享了！你倒是为开源做点贡献啊

**Comment by KylinMountain** [comment]
你开源挺好 但不必用在这个国际项目上提issue还特地弄个中文标题来吸引中国人吧？

我提了几个pr被合并了 怎么就没做贡献了？喷也要找好角度。

**Comment by win4r** [comment]
> 你开源挺好 但不必用在这个国际项目上提issue还特地弄个中文标题来吸引中国人吧？
> 
> 我提了几个pr被合并了 怎么就没做贡献了？喷也要找好角度。

所以你在喷什么？我在issue里用中文怎么就割韭菜了？
