### ISSUE TITLE
[Feature Request]: <title> The model may generate a json string in markdown format

### ISSUE THREAD

**Issue by lwdnxu** [microsoft/graphrag#582]
### Is your feature request related to a problem? Please describe.

The model may generate a json string in markdown format

### Describe the solution you'd like

Solution: Replace markdown syntax with re

```python
import re
if re.match(r'```json\n.*\n```', output, re.DOTALL):
    output = re.search(r'```json\n(.*)\n```', output, re.DOTALL).group(1)
return LLMOutput(output=output)
```

![1721117865192](https://github.com/user-attachments/assets/338aba55-a136-43e3-8d9e-32bddd5fa3fe)

After use, the entire workflow can be completed, as shown in the figure
![1721118013529](https://github.com/user-attachments/assets/6cb15c02-dbdb-44c3-bb62-ed3a519a74fb)

**Comment by lwdnxu** [comment]
修改一下
```python
try:
    if re.match(r'```json\n.*\n```', output, re.DOTALL):
        output = re.search(r'```json\n(.*)\n```', output, re.DOTALL).group(1)
except:
    pass
```

**Comment by kShines** [comment]
Suggest submission, the prompt has been modified many times but still cannot be formatted correctly.

**Comment by lwdnxu** [comment]
> Suggest submission, the prompt has been modified many times but still cannot be formatted correctly.建议提交，提示已修改多次但仍无法正确格式化。

I also tried to modify the prompt words to make the output more json instead of markdown, but I found that I couldn't do it, so I modified the source code.

**Comment by natoverse** [comment]
We have resolved several issues related to text encoding and JSON parsing that are rolled up into version [0.2.2](https://github.com/microsoft/graphrag/releases/tag/v0.2.2). Please try again with that version and re-open if this is still an issue.
