### ISSUE TITLE
[BUG]: Errors occurred during the pipeline run, see logs for more details.

### ISSUE THREAD

**Issue by Jumbo-zczlbj0** [microsoft/graphrag#583]
### Describe the bug

"Sometimes, running the command `python3 -m graphrag.index --root ./ragtest` results in the error 'Errors occurred during the pipeline run, see logs for more details,' even though no configuration changes were made. This issue may occur after restarting the computer. I have tried deleting the original environment and creating a new one. Sometimes it works well, and sometimes it doesn't."

The previous model was running smoothly and had successfully answered my questions. And my Ollama is functioning properly and the model has been downloaded.

I am a beginner, so I might not understand everything fully. Please bear with me

![Screenshot from 2024-07-16 04-19-19](https://github.com/user-attachments/assets/64753610-51c8-482d-901c-aead333027ad)

settings.yaml:
![Screenshot from 2024-07-16 04-12-24](https://github.com/user-attachments/assets/6c41eae6-18d6-423d-ad38-625c4e216892)
![Screenshot from 2024-07-16 04-12-15](https://github.com/user-attachments/assets/e0a6e548-073a-43c8-bd30-bf356103ecf4)

log: (ragtest/output/20240716-034934/reports/indexing-engine.log)

![Screenshot from 2024-07-16 04-16-05](https://github.com/user-attachments/assets/56ec7fab-faa2-4275-bc8d-c0cb3c230fcd)

![Screenshot from 2024-07-16 04-16-15](https://github.com/user-attachments/assets/8c5705e5-e8ef-4bd6-ad1c-133af22b6855)

[indexing-engine.log](https://github.com/user-attachments/files/16245363/indexing-engine.log)

### Steps to reproduce

1. Run Lm-studio 

2. chmod +x LM_Studio-0.2.27.AppImage

3. python3 -m graphrag.index --root ./ragtest

### Expected Behavior

I expect the LLM and embedding to process my data correctly

### Additional Information

- GraphRAG Version: 0.1.1 ( pip install graphrag )
- Operating System: Ubuntu 22.04
- Python Version: 3.12.4
- llm: ollama/gemma2:latest
- embeddings: lm-studio (nomic-embed-text-v1.5.Q5_K_M.gguf)

**Comment by myyourgit** [comment]
To: Jumbo:
how to run chmod +x LM_Studio-0.2.27.AppImage in windows 10?

I can not find LM_Studio-0.2.27.AppImage file in LM_Studio installation directory. If this is a *.exe file?

thanks

**Comment by myyourgit** [comment]
To: Jumbo:
I use your setting.yaml, run LM_studio, but python -m graphrag.index --root ./ragtest could not run correctly. 

And suggestion about setting.yaml?

  in logs, api_key is not recognized.
 "llm": {
        "api_key": "REDACTED, length 6",
        "type": "openai_chat",
        "model": "gemma2:latest",

Thanks
Quanling.

**Comment by Jumbo-zczlbj0** [comment]
> To: Jumbo: how to run chmod +x LM_Studio-0.2.27.AppImage in windows 10?
> 
> I can not find LM_Studio-0.2.27.AppImage file in LM_Studio installation directory. If this is a *.exe file?
> 
> thanks

I use Lm_studio on an Ubuntu system. You can download the Windows version from the official website: https://lmstudio.ai

**Comment by myyourgit** [comment]
> > To: Jumbo: how to run chmod +x LM_Studio-0.2.27.AppImage in windows 10?
> > I can not find LM_Studio-0.2.27.AppImage file in LM_Studio installation directory. If this is a *.exe file?
> > thanks
> 
> I use Lm_studio on an Ubuntu system. You can download the Windows version from the official website: https://lmstudio.ai

I use windows10. In windows, I just run LM_Studio, I think  this is OK.

**Comment by Jumbo-zczlbj0** [comment]
> To: Jumbo: I use your setting.yaml, run LM_studio, but python -m graphrag.index --root ./ragtest could not run correctly.
> 
> And suggestion about setting.yaml?
> 
> in logs, api_key is not recognized. "llm": { "api_key": "REDACTED, length 6", "type": "openai_chat", "model": "gemma2:latest",
> 
> Thanks

I don't know if you have installed Ollama. I referred to this video: https://youtu.be/BLyGDTNdad0?si=Pvx1og9aD_5fmZa3

**Comment by Jumbo-zczlbj0** [comment]
I installed graphrag in Docker to avoid this bug. 

I am using the official NVIDIA image (CUDA =12.2, Ubuntu22.04, devel)

By the way, LM_Studio can be replaced with llama.cpp.

**Comment by myyourgit** [comment]
> > To: Jumbo: I use your setting.yaml, run LM_studio, but python -m graphrag.index --root ./ragtest could not run correctly.
> > And suggestion about setting.yaml?
> > in logs, api_key is not recognized. "llm": { "api_key": "REDACTED, length 6", "type": "openai_chat", "model": "gemma2:latest",
> > Thanks
> 
> I don't know if you have installed Ollama. I referred to this video: https://youtu.be/BLyGDTNdad0?si=Pvx1og9aD_5fmZa3

Hi,Jumbo:
thanks.

in ollama directory, I run
ollama pull gemma2:9b

ollama run gemma2:9b
it works.

but the problem is that when running below command

curl http://localhost:11434/v1/chat/completions  

the result is:
404 page not found

this means that gemma2 port is not recognized.

**Comment by Jumbo-zczlbj0** [comment]
> > > To: Jumbo: I use your setting.yaml, run LM_studio, but python -m graphrag.index --root ./ragtest could not run correctly.
> > > And suggestion about setting.yaml?
> > > in logs, api_key is not recognized. "llm": { "api_key": "REDACTED, length 6", "type": "openai_chat", "model": "gemma2:latest",
> > > Thanks
> > 
> > 
> > I don't know if you have installed Ollama. I referred to this video: https://youtu.be/BLyGDTNdad0?si=Pvx1og9aD_5fmZa3
> 
> Hi,Jumbo: thanks.
> 
> in ollama directory, I run ollama pull gemma2:9b
> 
> ollama run gemma2:9b it works.
> 
> but the problem is that when running below command
> 
> curl http://localhost:11434/v1/chat/completions
> 
> the result is: 404 page not found
> 
> this means that gemma2 port is not recognized.


Please refer to the official way：https://github.com/ollama/ollama/blob/main/docs/api.md

For example:
curl http://localhost:11434/api/chat -d '{
  "model": "gemm2:latest",
  "messages": [
    { "role": "user", "content": "hi" }
  ]
}'


![IMG_7056](https://github.com/user-attachments/assets/d15ad309-e74e-4d73-a30d-c2d80540d71d)

**Comment by natoverse** [comment]
Consolidating alternate model issues here: https://github.com/microsoft/graphrag/issues/657
