### ISSUE TITLE
[Issue]: What is the process for removing and revising outdated documents?

### ISSUE THREAD

**Issue by BlingBunny** [microsoft/graphrag#585]

**Comment by natoverse** [comment]
At the moment there is no "index update" process, so you may need to re-index. However, we do aggresively cache outputs of LLM calls and the pipeline steps, so if you don't change your parameters you can avoid quite a lot of the indexing with subsequent runs. We'll add more content to the docs to help clarify this.

**Comment by natoverse** [comment]
Consolidating incremental updates with #741
