### ISSUE TITLE
Failed with Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by rudadasir** [microsoft/graphrag#587]
### Describe the issue

when runing  `python -m graphrag.index --init --root ./ragtest`

Failed with: Illegal instruction (core dumped)

### Additional Information

- GraphRAG Version:v0.1.1
- Operating System:ubuntu22.04
- Python Version:Python 3.10.12
- Related Issues:

**Comment by tonisi** [comment]
So how to fix this?

**Comment by kwjlhh** [comment]
hello, i have encountered the same problem while trying to build and run a docker image, I wonder how to fix the problem, thanks
