### ISSUE TITLE
[Issue]:  uvloop Dependency

### ISSUE THREAD

**Issue by Shashank0510** [microsoft/graphrag#589]
### Describe the issue

I am unable to install raggraph package, it throws an error - "graphrag is not installable because it requires
   └─ uvloop >=0.19.0,<0.20.0 , which does not exist (perhaps a missing channel)." Python version - 3.10.x 
and trying to install via miniforge. Please let me know how this issue could be solved. Operating System - Windows

### Additional Information

- GraphRAG Version:
- Operating System: Windows 10
- Python Version: 3.10.x
- Related Issues:

**Comment by AlonsoGuevara** [comment]
Hi @Shashank0510 
After looking around a bit, I found this is an issue with miniforge's channel:
https://anaconda.org/search?q=uvloop
Consider adding another channel to your pip installations so it has another source :)
