### ISSUE TITLE
[Bug]: Typing Extension Version - Dependency

### ISSUE THREAD

**Issue by Shashank0510** [microsoft/graphrag#591]
### Describe the bug

The latest version of typing-extension package available is 4.12.2 however the dependency states it requires a package typing extension >4.12.2. Can you please check ?

### Additional Information

- GraphRAG Version:
- Operating System: Windows
- Python Version: 3.10
- Related Issues:

**Comment by AlonsoGuevara** [comment]
Hi @Shashank0510 , it is set as typing-extension = "^4.12.2"
[Here](https://github.com/microsoft/graphrag/blob/309abc982f158c38099c6098d30b35a20972d258/pyproject.toml#L83)

Can you share any more details on the error you're getting?

**Comment by Shashank0510** [comment]
Hi Team,

I faced the following error - " Could not find the package distribution
"while installing through pip.

However, the work around I worked was installing the
typing_extensions=4.12.2 whl file.

Reproducability :

pip install graphrag

Python Version : 3.10

Operating System : Windows

I was using miniforge.


Hope this helps.

**Comment by AlonsoGuevara** [comment]
Hi @Shashank0510 
As in the uvloop issue, this seems to be related to miniforge's channel
https://anaconda.org/search?q=typing_extensions
