### ISSUE TITLE
[Issue]: Why do we keep the highest community level？

### ISSUE THREAD

**Issue by kShines** [microsoft/graphrag#600]
### Describe the issue
I think we should keep the community id list, not the level
Since the community id is required later in calculating the report weight, the level does not seem to make sense
```    
    entity_df = cast(pd.DataFrame, entity_df[["title", "degree", "community", "level"]]).rename(
        columns={"title": "name", "degree": "rank"}
    )

    entity_df["community"] = entity_df["community"].fillna(-1)
    entity_df["community"] = entity_df["community"].astype(int)
    entity_df["rank"] = entity_df["rank"].astype(int)

    # for duplicate entities, keep the one with the highest community level
    entity_df["community"] = entity_df["community"].apply(lambda x: str(x))
    entity_df = (
        entity_df.groupby(["name", "rank"])
        .agg({"community": lambda x: list(x)})
        .reset_index()
    )
```

![image](https://github.com/user-attachments/assets/1892f9fe-92e2-42f5-b9f4-4f4a1cddab1a)

![image](https://github.com/user-attachments/assets/708ef9ab-0a6c-49d6-83f0-2ad64181bfe0)

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
Moved to Q&A thread: https://github.com/microsoft/graphrag/discussions/716
