### ISSUE TITLE
为什么我的中文input会出现英文entity

### ISSUE THREAD

**Issue by dustelf** [microsoft/graphrag#608]
### Logs and screenshots

![image](https://github.com/user-attachments/assets/cabf7fe2-3380-4f1c-ad20-73ca6e075350)

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by jgbradley1** [comment]
Please provide more detail about the bug you are experiencing.

**Comment by dustelf** [comment]
my 

> 请提供有关您遇到的错误的更多详细信息。

My input files are all in Chinese, but the extracted entities are in English, and the descriptions are also in English
![image](https://github.com/user-attachments/assets/abeb8955-d749-4c50-9331-322e2468c6f0)

**Comment by WeiminLee** [comment]
You should change the default prompt for entity extraction.

**Comment by dustelf** [comment]
> You should change the default prompt for entity extraction.
I've changed it before, but English still appears.
![image](https://github.com/user-attachments/assets/d84f7b64-885b-4c8c-8efe-472b9a6ffcb7)

**Comment by Trip1ewhy** [comment]
在query那边还有几个prompt是英文的

**Comment by dustelf** [comment]
> 在query那边还有几个prompt是英文的

都改了呀

**Comment by WeiminLee** [comment]
把全部的prompt 改成中文，就可以了。然后自己定义好entity type

**Comment by natoverse** [comment]
Consolidating language support issues here: #696
