### ISSUE TITLE
[Issue]: Entra ID based authentication support. 

### ISSUE THREAD

**Issue by bulutmf** [microsoft/graphrag#614]
### Describe the issue

Is there a way to use Entra ID based authentication for Azure Open AI resource instead of token based auth? 

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by bulutmf** [comment]
Checking the code, I realized that leaving the `api_key` empty in `settings.yaml` file seems to do the job. Would be great to have this in the documentation.

**Comment by AlonsoGuevara** [comment]
Will make sure to put this in the docs! Thanks
