### ISSUE TITLE
[Issue]: <title> 为什么我觉得效果一般？

### ISSUE THREAD

**Issue by OKC13** [microsoft/graphrag#620]
### Describe the issue

你们跑起来感受如何，我感觉又慢又差

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by daijun4you** [comment]
你需要先 prompt_tunning，再去构建你的知识图谱，效果会好很多

**Comment by OKC13** [comment]
> 你需要先 prompt_tunning，再去构建你的知识图谱，效果会好很多

我是用的qwen2-7B，请问大佬说的prompt_tunning是什么

**Comment by OKC13** [comment]
> 你需要先 prompt_tunning，再去构建你的知识图谱，效果会好很多

我有提供ICL，给了示例。请问中文场景下，需要修改原prompt中的示例吗

**Comment by Trip1ewhy** [comment]
> > 你需要先 prompt_tunning，再去构建你的知识图谱，效果会好很多
> 
> 我有提供ICL，给了示例。请问中文场景下，需要修改原prompt中的示例吗

要修改的，包括query那边还有几个prompt可能也要翻译成中文。而且7B跑的图谱应该效果一般吧，中文感觉豆包好些

**Comment by Bai1026** [comment]
The prompt template should be modified based on your dataset~
This could be referred at their blog

**Comment by zhangfulei6521** [comment]
大佬你咋对接的通义千问 我试过了 深度 月之暗面 豆包  3.5 都可以 唯独 千问不对 一直是Columns must be same length as key这个错误

**Comment by OKC13** [comment]
我ollama 本地的服务



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月20日(周六) 中午1:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [microsoft/graphrag] [Issue]: <title&gt; 为什么我觉得效果一般？ (Issue #620)




 
大佬你咋对接的通义千问 我试过了 深度 月之暗面 豆包  3.5 都可以 唯独 千问不对 一直是Columns must be same length as key这个错误

**Comment by Bai1026** [comment]
有一個auto-generation的command 可以在他們blog找到！

**Comment by benben323** [comment]
> 大佬你咋对接的通义千问 我试过了 深度 月之暗面 豆包 3.5 都可以 唯独 千问不对 一直是Columns must be same length as key这个错误

这个应该是api服务没有配置好，看一下report log

**Comment by natoverse** [comment]
Consolidating alternate model issues here: #657

**Comment by super-ys** [comment]
> 大佬你咋对接的通义千问 我试过了 深度 月之暗面 豆包 3.5 都可以 唯独 千问不对 一直是Columns must be same length as key这个错误

请问你月之暗面怎么配的，能发个示例吗
