### ISSUE TITLE
[Issue]: <Errors occurred during the pipeline run> 

### ISSUE THREAD

**Issue by FlypigW** [microsoft/graphrag#622]
### Describe the issue

❌ create_base_entity_graph
None                                                                                                                                                                             
⠸ GraphRAG Indexer
├── Loading Input (text) - 1 files loaded (0 filtered) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00
├── create_base_text_units
├── create_base_extracted_entities
├── create_summarized_entities
└── create_base_entity_graph
❌ Errors occurred during the pipeline run, see logs for more details.

model: gemma2
embedding model: nomic-ai/nomic-embed-text-v1.5-GGUF/nomic-embed-text-v1.5.Q4_K_M.gguf

### Logs and screenshots

[indexing-engine.log](https://github.com/user-attachments/files/16303340/indexing-engine.log)

### Additional Information

- GraphRAG Version:0.1.1
- Operating System:win
- Python Version:3.10
- Related Issues:

**Comment by rushizirpe** [comment]
As you can see on LINE `#395` in `indexing-engine.log` you have provided, there's an `openai.AuthenticationError` saying `invalid API key`. Please cross-check `OPEN_API_KEY` in environment variables.

If you want to use open-source models, I've put together a repository for deploying models from HuggingFace to local endpoints, having similar functionality to OpenAI APIs. Here’s the link to the repo: https://github.com/rushizirpe/open-llm-server

Alternatively, I have created a Colab notebook for Graphrag: https://colab.research.google.com/drive/1uhFDnih1WKrSRQHisU-L6xw6coapgR51?usp=sharing
In Notebook, you will need GROQ_API_KEY if you don't have access to GPUs like A100. You can get it from here: https://console.groq.com/keys

**Comment by natoverse** [comment]
Consolidating alternate model issues here: https://github.com/microsoft/graphrag/issues/657

**Comment by yinzih** [comment]
![image](https://github.com/user-attachments/assets/8dd9598c-7388-4e04-8dd5-b8805b56b3c9)
请问，这个问题解决了嘛？
