### ISSUE TITLE
[Issue]: <title> How many prompts are there in total in this GraphRAG?

### ISSUE THREAD

**Issue by Trip1ewhy** [microsoft/graphrag#625]
### Describe the issue

Except for the 4 prompts in the /ragtest, I found 12 more prompts, while some of them are kind of same as the prompts in the /ragtest

**Comment by AlonsoGuevara** [comment]
Hi!
For indexing we make use of 4 main prompts, indeed. There are a couple more, here and there, but mainly for supporting gleanings and json cleanup.
For querying, we have 3 prompts.
For prompt tuning, we use 12 prompts.
