### ISSUE TITLE
[Feature Request]: <title>能不能prompt支持一下中文，感觉对中文提取实体非常差

### ISSUE THREAD

**Issue by Anthonyfhd** [microsoft/graphrag#626]
### Is your feature request related to a problem? Please describe.

能不能prompt支持一下中文，感觉对中文提取实体非常差

**Comment by KylinMountain** [comment]
要微调Prompt 如果生成的entity不和领域要求，还要手调Prompt。

**Comment by jgbradley1** [comment]
Yes the prompts will support other languages soon. This capability is in the repository now but was added after the initial release. You may build the Python wheel from source or we will be making a new release to PyPI very soon.

**Comment by WHG555** [comment]
When will Chinese be supported
