### ISSUE TITLE
GraphRAG Index procedure fail.... create_final_nodes.parquet not created..., faced the same problem , it could not find the create_final_nodes.parque. Please help!

### ISSUE THREAD

**Issue by SalihOsman1** [microsoft/graphrag#629]
### Discussed in https://github.com/microsoft/graphrag/discussions/554

<div type='discussions-op-text'>

<sup>Originally posted by **JB5579** July 14, 2024</sup>
I'm currently working on a project and I'm encountering a FileNotFoundError when trying to read the 'create_final_nodes.parquet' file. This file is expected to be created as part of the process, but it's not being found in the specified directory. However, other files ('create_base_extracted_entities.parquet' and 'create_base_text_units.parquet') were created successfully.

I've checked the file path and the file name, and they seem to be correct. I've also checked the process that creates these files, and it seems to be executing correctly.

Could anyone help me understand why this error is occurring and how I can fix it? Any insights or suggestions would be greatly appreciated.

Thank you in advance!</div>

**Comment by SalihOsman1** [comment]
I'm facing the same issue. Iam running my code in Google Colab environment. from types import MethodType
############## Global Query @@@@@@@@@@@@@@@@@@@@@@@
!python -m graphrag.query\
--root ./ragtest\
--method global\
"what is the main theme of this book"
Error: FileNotFoundError: [Errno 2] No such file or directory: '/content/ragtest/output/20240719-141928/artifacts/create_final_nodes.parquet'

**Comment by rushizirpe** [comment]
This usually occurs if the model provides a non-JSON response or if rate limiting is enforced (common with free APIs like GROQ). 
For such use cases, I've put together a repository for deploying open-source models locally, offering similar functionality to OpenAI APIs. Here’s the link to the repo: https://github.com/rushizirpe/open-llm-server 

Alternatively, I have created a Colab notebook which is available here: https://colab.research.google.com/drive/1uhFDnih1WKrSRQHisU-L6xw6coapgR51?usp=sharing

**Comment by natoverse** [comment]
Consolidating alternate model providers at issue #657
