### ISSUE TITLE
[Bug]: content regenerated when changing LLM model 

### ISSUE THREAD

**Issue by K2559** [microsoft/graphrag#636]
### Describe the bug

If you change your LLM model in the middle, such as you want to use different model for create_summarized_entities after create_base_extracted_entities, the code will restart the whole create_base_extracted_entities step untill all content are generated by the current LLM model. 

### Steps to reproduce

1. Go to a finished graphrag project
2. Change the model in the settings.yaml
3. run graphrag is the project folder
4. content will regenerate 

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by AlonsoGuevara** [comment]
Hi @K2559
Please use the --resume parameter to continue from a -previous execution.
For example:
`python -m graphrag.index --root your/root --resume 20240407-121341`

The resume value would be the folder id in your outputs that you want to resume from, it will make one every time you make a new run that starts anew.

Just for your consideration, changing LLM values will invalidate previous cache entries, as the LLM metadata is part of the cache key.

**Comment by K2559** [comment]
Hi @AlonsoGuevara

Invalidating previous cache entries is exactly what the problem I mentioned. It’s illogical to disregard caches created by other models. Considering the costs, it’s essential to utilize a combination of models. For instance, employing GPT-4o for relationship extraction followed by the use of GPT-4o-mini for summarizing headings is a practical approach.
