### ISSUE TITLE
[Issue]: <title> How does Graph RAG retrieve?

### ISSUE THREAD

**Issue by ILSparkle** [microsoft/graphrag#638]
### Describe the issue

It seems that in the Table 3 in the paper(https://arxiv.org/pdf/2404.16130), a certain level of communities will be traversed and the answer will be obtained. But the source code seems to select the communities where the entities related to the query are located?

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
Are you referring to local or global search, and do you have a code snippet that demonstrates the discrepancy?
