### ISSUE TITLE
[Issue]: <title> error: unrecognized arguments: --language English

### ISSUE THREAD

**Issue by prasantpoudel** [microsoft/graphrag#648]
### Describe the issue

I try to generate a tune prompt using 
python3 -m graphrag.prompt_tune --root ragtest --domain “manufacturing“ --method random --limit 10 --language English  --max-tokens 2048 --chunk-size 256 --no-entity-types --output GraphRAG/out

got the error 
usage: __main__.py [-h] [--root ROOT] [--domain DOMAIN] [--method {all,random,top}] [--limit LIMIT] [--max-tokens MAX_TOKENS] [--chunk-size CHUNK_SIZE] [--no-entity-types] [--output OUTPUT]
__main__.py: error: unrecognized arguments: --language English

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by jgbradley1** [comment]
This feature was added to graphrag after the `0.1.1` release. If you installed the package from PyPI, it will not have this feature available yet. To use the latest, you may clone the repo, build the wheel (run `poetry build` in the root directory of the repo), and `pop install` the wheel file.

If you prefer to wait, we will be making a new release very soon.
