### ISSUE TITLE
[Issue]: UnicodeEncodeError 

### ISSUE THREAD

**Issue by KazutaNakazawa** [microsoft/graphrag#649]
### Describe the issue

Following the steps below, I encountered an error after executing the command:
>python -m graphrag.index --init --root ./ragtest

https://microsoft.github.io/graphrag/posts/get_started/

### GraphRAG Config Used

↓inputfile
[book.txt](https://github.com/user-attachments/files/16331304/book.txt)

### Logs and screenshots

PS C:\Users\hoge> python -m graphrag.index --init --root ./ragtest
Initializing project at ./ragtest
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\hoge\AppData\Local\Programs\Python\Python312\Lib\site-packages\graphrag\index\__main__.py", line 68, in <module>
    index_cli(
  File "C:\Users\hoge\AppData\Local\Programs\Python\Python312\Lib\site-packages\graphrag\index\cli.py", line 90, in index_cli
    _initialize_project_at(root, progress_reporter)
  File "C:\Users\hoge\AppData\Local\Programs\Python\Python312\Lib\site-packages\graphrag\index\cli.py", line 196, in _initialize_project_at
    file.write(GRAPH_EXTRACTION_PROMPT)
UnicodeEncodeError: 'cp932' codec can't encode character '\u2014' in position 5356: illegal multibyte sequence
⠋ GraphRAG Indexer

### Additional Information

- GraphRAG Version:0.1.1
- Python Version:3.12.0

**Comment by SimonZhuo1990** [comment]
Same problem, and I tried to add some arguments at line 195 of cli.py.
with entity_extraction.open("w") as file:
→
with entity_extraction.open("w",-1,"utf-8") as file:
by this way, no error happened and it seems that some files created in prompts folder.

**Comment by jgbradley1** [comment]
We have a [PR](https://github.com/microsoft/graphrag/pull/639) that should resolve this problem.

We’ve had users report that this is a common problem for Windows users in China (potentially other parts of the world - I don’t know). The default encoding used by Python in those regions is not `utf-8`.

If you have time, I would greatly appreciate if you could take a look at that PR and test out the Python package.

You can build the Python wheel by running `poetry build` in the root directory in the repo. It will create a `dist` directory with a wheel file that you can `pip install` directly.

**Comment by KazutaNakazawa** [comment]
@SimonZhuo1990 
Thank you very much. The method you taught me resolved the error.

**Comment by KazutaNakazawa** [comment]
> with entity_extraction.open("w",-1,"utf-8") as file:
by this way, no error happened and it seems that some files created in prompts folder.

The above method caused an error in subsequent processing.
It was confirmed that setting the following environment variable can avoid this issue:

PYTHONUTF8=1

**Comment by rushizirpe** [comment]
The error you're hitting is because the system's default cp932 codec can't handle certain Unicode characters. To fix this, you can change the input file encoding to UTF-8. You can either set the environment variable PYTHONUTF8=1 to force Python to use UTF-8 or modify the file to encoding='utf-8' manually.

**Comment by natoverse** [comment]
GraphRAG version 0.2.0 has been released, which includes the PR @jgbradley1 mentioned. Please try updating and let us know if you still have the issue.

**Comment by KazutaNakazawa** [comment]
I have confirmed that this issue has been resolved in version 0.2.0. I will close the issue.
