### ISSUE TITLE
[Issue]:Preparing metadata (pyproject.toml)

### ISSUE THREAD

**Issue by TWChenYI002** [microsoft/graphrag#656]
### Describe the issue

When I install graphrag, I get an error, thanks

### Steps to reproduce

1. pyenv virtualenv 3.10.14 myenv-3.10.14
2. pyenv activate myenv-3.10.14
3. pip install graphrag

### Logs and screenshots

![image](https://github.com/user-attachments/assets/b2d5a3ac-fa42-4292-bac5-ae24fdcf5e7f)

### Additional Information

- GraphRAG Version: latest version
- Operating System: macOS Big Sur apple M1
- Python Version: 3.10.14
- Related Issues:

**Comment by jgbradley1** [comment]
This does not look like an issue with the `graphrag` package. The error log indicates that one of the dependencies `graphrag` uses requires gfortran to be installed and it is not.
