### ISSUE TITLE
How to dynamically select local and global search methods in action?

### ISSUE THREAD

**Issue by Nuclear6** [microsoft/graphrag#662]
As shown in the title

**Comment by natoverse** [comment]
Are you asking about how to use them as a python library in your application versus the CLI examples?

**Comment by Nuclear6** [comment]
Yes, if I want to use this project to build a RAG system, the user only has one input box. How should the system determine whether to call the local or global query method?

**Comment by RobertHH-IS** [comment]
Use a LLM router... use the descriptions provided in the docs of both options to have an LLM select which option is best for the question.  If your token rich, just call both every time and have the final LLM utilize whatever knowledge was provided by both.
