### ISSUE TITLE
[Issue]: Wrong link in document

### ISSUE THREAD

**Issue by albaNnaksqr** [microsoft/graphrag#666]
### Describe the issue

the links you provided in docsite/posts/get_started.md (https://github.com/microsoft/graphrag/blob/main/posts/developing for example) will return a **404 Page Not Found** .

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
Links in the docsite markdown files are intended to work with the generated and deployed docsite, which uses the eleventy framework. The cited link, for example, is on the deployed page here: https://microsoft.github.io/graphrag/posts/get_started/, and links to the developing page here: https://microsoft.github.io/graphrag/posts/developing/
