### ISSUE TITLE
Chinese entity does not match the description of the entity

### ISSUE THREAD

**Issue by pg572** [microsoft/graphrag#667]
<img width="932" alt="Screenshot 2024-07-23 at 3 52 34 PM" src="https://github.com/user-attachments/assets/bd93a885-03eb-496a-bf52-b068ec87abdf">
<img width="939" alt="Screenshot 2024-07-23 at 3 52 03 PM" src="https://github.com/user-attachments/assets/e9f4140a-fef1-46c1-a0e6-2b445fc32472">
<img width="930" alt="Screenshot 2024-07-23 at 3 51 26 PM" src="https://github.com/user-attachments/assets/e3530e26-4273-49ed-b09d-d21a18eb9a55">
这三张图中是一些出现问题的例子，description中的实体名字变成了别的东西，而且导致description自身也不正确。有人知道为什么吗？目前别的地方没有看到类似的情况，只有entity里有出现。

**Comment by jgbradley1** [comment]
Posting an english translation of the original post using Google Translate.

> These three pictures are some examples of problems. The entity name in the description becomes something else, and the description itself is incorrect. Does anyone know why? At present, we have not seen similar situations elsewhere, only in entities.

**Comment by natoverse** [comment]
Consolidating language support issues here: #696
