### ISSUE TITLE
[Issue]: The prompt for each task request is too long

### ISSUE THREAD

**Issue by hust-zXX** [microsoft/graphrag#668]
### Describe the issue

Taking the demo file A Christmas Carol by Charles Dickens as an example, after the knowledge graph is built, the tokens consumed by executing a question are almost the same as the entire article, reaching more than 100,000.

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by AlonsoGuevara** [comment]
Hi @hust-zXX
If you're running Global Search this would be expected as this is an extensive operation over the Knowledge Graph.
You can also run Local Search, which leverages embeddings to operate over "closer" entities.
