### ISSUE TITLE
[Issue]: <Why pip install got 0.0.0 version> 

### ISSUE THREAD

**Issue by handsome-fish** [microsoft/graphrag#681]
### Describe the issue

When execute commands "pip install graphrag"
Want version 0.0.1 but got 0.0.0, WHY?

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by jgbradley1** [comment]
Are you pulling from the main [PyPI](https://pypi.org/project/graphrag)? You can also try to specify the version `pip install graphrag==0.1.1`.

**Comment by cefege** [comment]
I have the exact same issuen Macbook M1 Air, 8 Gb.
