### ISSUE TITLE
Error executing verb \"orderby\" in create_base_text_units, Error running pipeline!

### ISSUE THREAD

**Issue by kapa2004** [microsoft/graphrag#692]
### Describe the issue

Just tried to load in a simple txt file.

In the terminal is goes until :
⠼ GraphRAG Indexer
├── Loading Input (text) - 1 files loaded (0 filtered) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00
├── create_base_text_units
├── create_base_extracted_entities
├── create_summarized_entities
└── create_base_entity_graph
❌ Errors occurred during the pipeline run, see logs for more details.

### GraphRAG Config Used

encoding_model: cl100k_base
skip_workflows: []
llm:
  api_key: ${GRAPHRAG_API_KEY}
  type: openai_chat # or azure_openai_chat
  model: gpt-4-turbo-preview
  model_supports_json: true # recommended if this is available for your model.
  # max_tokens: 4000
  # request_timeout: 180.0
  # api_base: https://<instance>.openai.azure.com
  # api_version: 2024-02-15-preview
  # organization: <organization_id>
  # deployment_name: <azure_model_deployment_name>
  # tokens_per_minute: 150_000 # set a leaky bucket throttle
  # requests_per_minute: 10_000 # set a leaky bucket throttle
  # max_retries: 10
  # max_retry_wait: 10.0
  # sleep_on_rate_limit_recommendation: true # whether to sleep when azure suggests wait-times
  # concurrent_requests: 25 # the number of parallel inflight requests that may be made
  # temperature: 0 # temperature for sampling
  # top_p: 1 # top-p sampling
  # n: 1 # Number of completions to generate

parallelization:
  stagger: 0.3
  # num_threads: 50 # the number of threads to use for parallel processing

async_mode: threaded # or asyncio

embeddings:
  ## parallelization: override the global parallelization settings for embeddings
  async_mode: threaded # or asyncio
  llm:
    api_key: ${GRAPHRAG_API_KEY}
    type: openai_embedding # or azure_openai_embedding
    model: text-embedding-3-small
    # api_base: https://<instance>.openai.azure.com
    # api_version: 2024-02-15-preview
    # organization: <organization_id>
    # deployment_name: <azure_model_deployment_name>
    # tokens_per_minute: 150_000 # set a leaky bucket throttle
    # requests_per_minute: 10_000 # set a leaky bucket throttle
    # max_retries: 10
    # max_retry_wait: 10.0
    # sleep_on_rate_limit_recommendation: true # whether to sleep when azure suggests wait-times
    # concurrent_requests: 25 # the number of parallel inflight requests that may be made
    # batch_size: 16 # the number of documents to send in a single request
    # batch_max_tokens: 8191 # the maximum number of tokens to send in a single request
    # target: required # or optional
  

chunks:
  size: 1200
  overlap: 100
  group_by_columns: [id] # by default, we don't allow chunks to cross documents
    
input:
  type: file # or blob
  file_type: text # or csv
  base_dir: "input"
  file_encoding: utf-8
  file_pattern: ".*\\.txt$"

cache:
  type: file # or blob
  base_dir: "cache"
  # connection_string: <azure_blob_storage_connection_string>
  # container_name: <azure_blob_storage_container_name>

storage:
  type: file # or blob
  base_dir: "output/${timestamp}/artifacts"
  # connection_string: <azure_blob_storage_connection_string>
  # container_name: <azure_blob_storage_container_name>

reporting:
  type: file # or console, blob
  base_dir: "output/${timestamp}/reports"
  # connection_string: <azure_blob_storage_connection_string>
  # container_name: <azure_blob_storage_container_name>

entity_extraction:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  prompt: "prompts/entity_extraction.txt"
  entity_types: [organization,person,geo,event]
  max_gleanings: 1

summarize_descriptions:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

claim_extraction:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  # enabled: true
  prompt: "prompts/claim_extraction.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

community_reports:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  prompt: "prompts/community_report.txt"
  max_length: 2000
  max_input_length: 8000

cluster_graph:
  max_cluster_size: 10

embed_graph:
  enabled: false # if true, will generate node2vec embeddings for nodes
  # num_walks: 10
  # walk_length: 40
  # window_size: 2
  # iterations: 3
  # random_seed: 597832

umap:
  enabled: false # if true, will generate UMAP embeddings for nodes

snapshots:
  graphml: false
  raw_entities: false
  top_level_nodes: false

local_search:
  # text_unit_prop: 0.5
  # community_prop: 0.1
  # conversation_history_max_turns: 5
  # top_k_mapped_entities: 10
  # top_k_relationships: 10
  # llm_temperature: 0 # temperature for sampling
  # llm_top_p: 1 # top-p sampling
  # llm_n: 1 # Number of completions to generate
  # max_tokens: 12000

global_search:
  # llm_temperature: 0 # temperature for sampling
  # llm_top_p: 1 # top-p sampling
  # llm_n: 1 # Number of completions to generate
  # max_tokens: 12000
  # data_max_tokens: 12000
  # map_max_tokens: 1000
  # reduce_max_tokens: 2000
  # concurrency: 32

### Logs and screenshots

{"type": "error", "data": "Error executing verb \"orderby\" in create_base_text_units: 'id'", "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\\u00c1ronHet\u00e9nyi\\graphrag\\.venv\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 410, in _execute_verb\n    result = node.verb.func(**verb_args)\n  File \"C:\\Users\\\u00c1ronHet\u00e9nyi\\graphrag\\.venv\\lib\\site-packages\\datashaper\\engine\\verbs\\orderby.py\", line 32, in orderby\n    output = input_table.sort_values(by=columns, ascending=ascending)\n  File \"C:\\Users\\\u00c1ronHet\u00e9nyi\\graphrag\\.venv\\lib\\site-packages\\pandas\\core\\frame.py\", line 7189, in sort_values\n    k = self._get_label_or_level_values(by[0], axis=axis)\n  File \"C:\\Users\\\u00c1ronHet\u00e9nyi\\graphrag\\.venv\\lib\\site-packages\\pandas\\core\\generic.py\", line 1911, in _get_label_or_level_values\n    raise KeyError(key)\nKeyError: 'id'\n", "source": "'id'", "details": null}
{"type": "error", "data": "Error running pipeline!", "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\\u00c1ronHet\u00e9nyi\\graphrag\\graphrag\\index\\run.py\", line 323, in run_pipeline\n    result = await workflow.run(context, callbacks)\n  File \"C:\\Users\\\u00c1ronHet\u00e9nyi\\graphrag\\.venv\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 369, in run\n    timing = await self._execute_verb(node, context, callbacks)\n  File \"C:\\Users\\\u00c1ronHet\u00e9nyi\\graphrag\\.venv\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 410, in _execute_verb\n    result = node.verb.func(**verb_args)\n  File \"C:\\Users\\\u00c1ronHet\u00e9nyi\\graphrag\\.venv\\lib\\site-packages\\datashaper\\engine\\verbs\\orderby.py\", line 32, in orderby\n    output = input_table.sort_values(by=columns, ascending=ascending)\n  File \"C:\\Users\\\u00c1ronHet\u00e9nyi\\graphrag\\.venv\\lib\\site-packages\\pandas\\core\\frame.py\", line 7189, in sort_values\n    k = self._get_label_or_level_values(by[0], axis=axis)\n  File \"C:\\Users\\\u00c1ronHet\u00e9nyi\\graphrag\\.venv\\lib\\site-packages\\pandas\\core\\generic.py\", line 1911, in _get_label_or_level_values\n    raise KeyError(key)\nKeyError: 'id'\n", "source": "'id'", "details": null}

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by The-uyu** [comment]
请问您是如何解决这个问题的

**Comment by genriq** [comment]
Hi! Solution?

**Comment by Ljango** [comment]
hi？

**Comment by Friman04** [comment]
same

**Comment by sbhuttan** [comment]
Instead of using > operator, that includes everything returned from the website, -o should be used for downloading the file. Changing to -o attribute fixes the error. 

Change this - 
curl https://www.gutenberg.org/cache/epub/24022/pg24022.txt > ./ragtest/input/book.txt
To this - 
curl https://www.gutenberg.org/cache/epub/24022/pg24022.txt -o ./ragtest/input/book.txt

**Comment by sbhuttan** [comment]
Instead of using > operator, that includes everything returned from the website, -o should be used for downloading the file. Changing to -o attribute fixes the error.

Change this -
curl https://www.gutenberg.org/cache/epub/24022/pg24022.txt > ./ragtest/input/book.txt
To this -
curl https://www.gutenberg.org/cache/epub/24022/pg24022.txt -o ./ragtest/input/book.txt

**Comment by RangaRS** [comment]
> The.txt set format to UTF-8.

This fixed the issue for me. Thank you.

How to change format> --> just open the file in a notpad and save it again, change the format to UTF-8.

**Comment by suckgeun** [comment]
> Instead of using > operator, that includes everything returned from the website, -o should be used for downloading the file. Changing to -o attribute fixes the error.
> 
> Change this - curl https://www.gutenberg.org/cache/epub/24022/pg24022.txt > ./ragtest/input/book.txt To this - curl https://www.gutenberg.org/cache/epub/24022/pg24022.txt -o ./ragtest/input/book.txt

thank you this fixed my problem
