### ISSUE TITLE
[Issue]: Trying to understand how GraphRAG works

### ISSUE THREAD

**Issue by yhshu** [microsoft/graphrag#695]
### Is there an existing issue for this?

- [ ] I have searched the existing issues
- [ ] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

I've checked the GraphRAG documentation, but I'm afraid I still have some questions I'd like to ask.

1. What is the relationship between the question generation module and global/local query module? I can't correlate them at the moment.
2. How is retrieval and re-reranking implemented for local queries? I understand retrieval by pre-computed embedding and reranking by calling LLM?

Thank you for your answering!

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
Copied to Q&A here: https://github.com/microsoft/graphrag/discussions/721
