### ISSUE TITLE
[Feature Request]: Drop in Solution with Azure Deployed OpenAI

### ISSUE THREAD

**Issue by mirojs** [microsoft/graphrag#703]
### Is your feature request related to a problem? Please describe.

Hello,

It would help folks to switch from vector RAG to GraphRAG if there could be a drop in replacement besides some configurations. 

Thanks!

### Describe the solution you'd like

Would this be feasible on Azure deployed app using Azure OpenAI?

**Comment by natoverse** [comment]
Have you looked at the Solution Accelerator repo? https://github.com/Azure-Samples/graphrag-accelerator

**Comment by mirojs** [comment]
Got it, thanks!
