### ISSUE TITLE
[Issue]: Why is system role used in the history instead of assistant?

### ISSUE THREAD

**Issue by ChihchengHsieh** [microsoft/graphrag#749]
### Is there an existing issue for this?

- [x] I have searched the existing issues
- [x] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

In the class `OpenAIHistoryTrackingLLM`, the history for next iteration is prepared as following:

```
       return LLMOutput(
            output=output.output,
            json=output.json,
            history=[
                *history,
                {"role": "user", "content": input},
                {"role": "system", "content": output.output},
            ],
        )
```

I'm wondering why the response from LLM is set as  {"role" : "system"} instead of  {"role" : "assistant"}? Is there a spefic reason of doing this or is it interchangeable? 

Best

**Comment by natoverse** [comment]
Yep, this is a bug - we noticed it this week too, and fixed it with https://github.com/microsoft/graphrag/pull/773
