### ISSUE TITLE
Extracting Entities from Legal Texts

### ISSUE THREAD

**Issue by yangxue-1** [microsoft/graphrag#755]
### Is there an existing issue for this?

- [ ] I have searched the existing issues
- [ ] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

Function: Questions and Answers Based on Chinese Legal Provisions
Model: based on qwen2:7b
Problem: The entities extracted from legal provisions are not accurate and comprehensive enough. How to optimize the extraction?

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:0.1.1
- Operating System:ubuntu 22.04
- Python Version:3.10
- Related Issues:qwen2:7b

**Comment by KylinMountain** [comment]
You can check my article about how to prompt and adjust the prompt in manually.

[GraphRAG失效？快用Prompt Tune适配文档的领域和语言](https://mp.weixin.qq.com/s/MdFY6ON-F8dzRhOk6bNokQ) and the other article about adjust the entity to what you want in my wechat 公众号。

**Comment by yangxue-1** [comment]
> You can check my article about how to prompt and adjust the prompt in manually.
> 
> [GraphRAG失效？快用Prompt Tune适配文档的领域和语言](https://mp.weixin.qq.com/s/MdFY6ON-F8dzRhOk6bNokQ) and the other article about adjust the entity to what you want in my wechat 公众号。

好的，我学习一下，非常感谢

**Comment by natoverse** [comment]
I also suggest trying the [auto-tuning function](https://microsoft.github.io/graphrag/posts/prompt_tuning/auto_prompt_tuning/) to tailor your entity extraction prompts to the specifics of your data domain before running ingest.

**Comment by yangxue-1** [comment]
> I also suggest trying the [auto-tuning function](https://microsoft.github.io/graphrag/posts/prompt_tuning/auto_prompt_tuning/) to tailor your entity extraction prompts to the specifics of your data domain before running ingest.

Ok,thanks very much.
