### ISSUE TITLE
[.env missing]: <After 'pip install' and initiation by the guidance>

### ISSUE THREAD

**Issue by xb8023** [microsoft/graphrag#758]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

After download and initiation, there's no '.env' file in the target derictory 

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by xb8023** [comment]
an issue about demonstration

**Comment by natoverse** [comment]
Try using the [init command](https://microsoft.github.io/graphrag/posts/config/init/), which will create a settings.yml file
