### ISSUE TITLE
[Issue]: <title> 

### ISSUE THREAD

**Issue by 1linS** [microsoft/graphrag#768]
### Is there an existing issue for this?

- [ ] I have searched the existing issues
- [ ] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

When using local search to obtain entities based on a query, the map_query_to_entities function utilizes the text_embedding_vectorstore.similarity_search_by_text to calculate similarity. Is this function calculating the similarity between the query and the description_embedding? Can it be replaced with the similarity calculation of the entities' embeddings?

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
The similarity search is comparing the query against the embeddings for the `entity.description` field. That is currently the only field that we compute embeddings for by default, and we have found good success with that as a way of matching relevant entities to a query
