### ISSUE TITLE
How to import existing neo4j knowledge graph data into this project for Q&A[Feature Request]: <title>

### ISSUE THREAD

**Issue by WanFeng123313** [microsoft/graphrag#775]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this feature is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate feature request, not just a question. If this is a question, please use the Discussions area.

**Comment by natoverse** [comment]
Great writeup here: https://towardsdatascience.com/integrating-microsoft-graphrag-into-neo4j-e0d4fa00714c

**Comment by WanFeng123313** [comment]
Sorry, what I meant was to be able to turn my existing neo4j knowledge graph into the data for this project and use it for question answering instead of graphrag into neo4j. I don't know if it will work

**Comment by rmd1710714107** [comment]
> Sorry, what I meant was to be able to turn my existing neo4j knowledge graph into the data for this project and use it for question answering instead of graphrag into neo4j. I don't know if it will work

did u resolve it?i have same problem.

**Comment by WanFeng123313** [comment]
> > Sorry, what I meant was to be able to turn my existing neo4j knowledge graph into the data for this project and use it for question answering instead of graphrag into neo4j. I don't know if it will work
> 
> did u resolve it?i have same problem.

You can try the thinking of the project: https://github.com/liuhuanyong/RAGOnMedicalKG
