### ISSUE TITLE
Error when running graphrag.index after enable claim_extraction [Bug]: <title>

### ISSUE THREAD

**Issue by mavershang** [microsoft/graphrag#776]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

After enabled claim_extraction, graphrag_index runs to error in create_final_covariates step.  Error as attached. It runs ok if I disable claim_extraction.

![image](https://github.com/user-attachments/assets/277a0164-52d0-48a2-868b-5373b3feeb08)

![image](https://github.com/user-attachments/assets/582e2216-f1fd-4abb-bc7b-df2dd543358d)

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by shaoqing404** [comment]
这个东西似乎不应该被启用。在社区中我被提示需要修改提示词才开启这个协变量。在没有新版本之前，我的建议是先关闭。
此外，graphrag对中文不太友好，需要更新中文分词器改善效果。
--------------

It seems that this thing should not be enabled. In the community I was prompted that I need to modify the prompt word to turn on this covariate. My suggestion is to turn it off before there is a new version. Also, graphrag is not very friendly to Chinese, and the Chinese word segmentation needs to be updated to improve the effect.

**Comment by 9prodhi** [comment]
I am unable to reproduce the issue on my end. Could you please provide additional details so that I can replicate the problem? Below is my current configuration:

```yaml
llm:
  api_key: ${GRAPHRAG_API_KEY}
  type: openai_chat # or azure_openai_chat
  model: mistral
  model_supports_json: true # Recommended if available for your model.
  api_base: http://localhost:11434/v1

parallelization:
  stagger: 0.3

async_mode: threaded # or asyncio

embeddings:
  async_mode: threaded # or asyncio
  llm:
    api_key: ${GRAPHRAG_API_KEY}
    type: openai_embedding # or azure_openai_embedding
    model: nomic-ai/nomic-embed-text-v1.5-GGUF

claim_extraction:
  enabled: true
  prompt: "prompts/claim_extraction.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

**Comment by huqianghui** [comment]
> I am unable to reproduce the issue on my end. Could you please provide additional details so that I can replicate the problem? Below is my current configuration:
> 
> ```yaml
> llm:
>   api_key: ${GRAPHRAG_API_KEY}
>   type: openai_chat # or azure_openai_chat
>   model: mistral
>   model_supports_json: true # Recommended if available for your model.
>   api_base: http://localhost:11434/v1
> 
> parallelization:
>   stagger: 0.3
> 
> async_mode: threaded # or asyncio
> 
> embeddings:
>   async_mode: threaded # or asyncio
>   llm:
>     api_key: ${GRAPHRAG_API_KEY}
>     type: openai_embedding # or azure_openai_embedding
>     model: nomic-ai/nomic-embed-text-v1.5-GGUF
> 
> claim_extraction:
>   enabled: true
>   prompt: "prompts/claim_extraction.txt"
>   description: "Any claims or facts that could be relevant to information discovery."
>   max_gleanings: 1
> ```

If  you use chinese documents，then I  think you can reproduce the same issue just like me as blow.

<img width="1665" alt="Screenshot 2024-08-02 at 10 02 24 AM" src="https://github.com/user-attachments/assets/94af43a7-28c9-4c69-af01-37533833d8d9">

**Comment by Guiwith** [comment]
I used english document,but the same erro.
![2024-08-05 152733](https://github.com/user-attachments/assets/280ad084-3c49-4a36-83ba-886f4f5f1192)

**Comment by shaoqing404** [comment]
这些问题在我这里并没有复现。我才用deepseek兼容了json格式的api，中文英文均正常

**Comment by AlonsoGuevara** [comment]
Folks, we recently added better support for non ASCII characters.
Can you confirm if this still happens on 0.3.0?

**Comment by shaoqing404** [comment]
> 伙计们，我们最近添加了对非 ASCII 字符的更好支持。您能否确认这在 0.3.0 上是否仍然发生？

为你进行了测试。0.3.0对非ASCII字符表现良好
