### ISSUE TITLE
Questions about relationship concepts.

### ISSUE THREAD

**Issue by MiratPH** [microsoft/graphrag#788]
### Description
![image](https://github.com/user-attachments/assets/9881191b-ae4f-420c-bcb9-85ea753e1f36)

I opened the generated GraphML files in Gephi, and unlike the entities, it seems that the relationships are not typed and only have descriptions. My questions are:

1.	Do these relationship descriptions play a role in the query process?
2.	Can I set typed relationships, as we do with entities, or is GraphRAG designed to work without relationship types?

Thanks.

### Checklist

- [x] I have searched for similar issues and didn't find any duplicates.
- [x] I have provided a clear and concise description of the issue.

**Comment by natoverse** [comment]
Moving to discussion https://github.com/microsoft/graphrag/discussions/792
