### ISSUE TITLE
I have implemented a web server with instant streaming output no need wait.

### ISSUE THREAD

**Issue by KylinMountain** [microsoft/graphrag#795]
### Describe the issue

you can check my project [graphrag](https://github.com/KylinMountain/graphrag)
you can check demo video: https://www.bilibili.com/video/BV113v8e6EZn/

## GraphRAG customized by KylinMountain
- I have added websever to support streaming output immediately.
- I have fixed error when using local embedding service like LM Studio
- I have fixed index error after prompt tune
- I have fixed the strategy not loaded when setting entity extraction using NLTK.
- I have added advice question api
- Support any desktop application or web application compatible with OpenAI SDK, support advice question

## GraphRAG 定制版

你可以参考演示视频：https://www.bilibili.com/video/BV113v8e6EZn/
- 我添加了Web服务器，以支持真即时流式输出。
- 我修复了使用本地嵌入服务（如LM Studio）时的错误。
- 我修复了提示调整后索引错误的问题。
- 我修复了在使用NLTK设置实体提取时策略未加载的问题。
- 我添加了建议问题API。
- 支持任意兼容OpenAI大模型桌面应用或者Web应用UI接入, 可以使用Cherry Studio 支持建议问题

### Logs and screenshots

![image](https://github.com/user-attachments/assets/7e8ea459-89de-4b8e-bdd7-525388ab6532)

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by KylinMountain** [comment]
![image](https://github.com/user-attachments/assets/9ae49054-8c4a-4585-8e06-e9ae16f29ff5)

**Comment by KylinMountain** [comment]
The link is accessable

![image](https://github.com/user-attachments/assets/9ea572d6-dab7-4b85-acf0-ae3168bf294b)

**Comment by natoverse** [comment]
Thanks for sharing @KylinMountain! Moving this to a new [Community tools](https://github.com/microsoft/graphrag/discussions/categories/community-tools) Discussion area: https://github.com/microsoft/graphrag/discussions/798 for long-term findability.
