### ISSUE TITLE
[Issue]: <title> Reason behind Generating the community report.

### ISSUE THREAD

**Issue by prasantpoudel** [microsoft/graphrag#806]
### Is there an existing issue for this?

- [ ] I have searched the existing issues
- [ ] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

Is there is any pdf or blog avaliable about this all the prompt and their usecases?

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
The community reports are used to answer questions with global search. The processis described in the [arxiv paper](https://arxiv.org/pdf/2404.16130) and briefly in the [global search docs](https://microsoft.github.io/graphrag/posts/query/0-global_search/).

**Comment by prasantpoudel** [comment]
done.
