### ISSUE TITLE
[Bug]: The Community Embedding step in the official documentation is not performed

### ISSUE THREAD

**Issue by chenweijia0925** [microsoft/graphrag#807]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

The Community Embedding step in the official documentation(https://microsoft.github.io/graphrag/posts/index/1-default_dataflow/) is not performed,I do not see the result of vectozation of the community embedding in create_final_community_reports.parquet file
![image](https://github.com/user-attachments/assets/1451fa9d-3389-49c4-ac3b-c999a05fb574)

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
All text fields flow through an optional embedding step, but only one is turned on by default, `entity.description`. We use the entity description embedding for local search, but there are no other places we use the other embeddings right now, so we turn them off the save time and expense. We have parameters in the config to turn on any of the embedding fields if you need them for other processes though - please see `GRAPHRAG_EMBEDDING_TARGET` and `GRAPHRAG_EMBEDDING_SKIP` if you need to enable others

**Comment by chenweijia0925** [comment]
> All text fields flow through an optional embedding step, but only one is turned on by default, `entity.description`. We use the entity description embedding for local search, but there are no other places we use the other embeddings right now, so we turn them off the save time and expense. We have parameters in the config to turn on any of the embedding fields if you need them for other processes though - please see `GRAPHRAG_EMBEDDING_TARGET` and `GRAPHRAG_EMBEDDING_SKIP` if you need to enable others

@natoverse, Thank you very much for your answer. Based on the above, I have a new question about how to configure to enable the Community Embedding. I do not find this configuration in the setting.yaml file

**Comment by natoverse** [comment]
This is the full list of fields that GraphRAG can embed:

- `text_unit.text`
- `document.raw_content`
- `entity.name`
- `entity.description`
- `relationship.description`
- `community.title`
- `community.summary`
- `community.full_content`

If you want to turn on selected fields, there is a two step process. First, set `GRAPHRAG_EMBEDDING_TARGET=all`. This will turn on every optional field. However, if you only want to add `community.summary` along with the default `entity.description`, you would skip _all of the others_: `GRAPHRAG_EMBEDDING_SKIP=text_unit.text,document.raw_content,entity.name,relationship.description,community.title,community.full_content`

The env vars map to settings.yml hierarchically, e.g.:

```
embeddings:
    target: "all"
    skip: [text_unit.text,...]
```
