### ISSUE TITLE
[Bug]: json_clean_up repair json faulty ，but increase index time and global search time 70-80%

### ISSUE THREAD

**Issue by xxll88** [microsoft/graphrag#818]
Although json_clean_up repair json faulty responses，it increases index time and global search time 70-80%
here are some time comparation :
v0.2.0 index time 35min , v0.2.1 62min
v0.2.0 global search time 45s , v0.2.1 75s
I want to back 0.2.0,  will  some json faulty responses will decrease search qulity ? 
I can't see big difference of global search result between v0.2.0 and v0.2.1

**Comment by AlonsoGuevara** [comment]
Addressing this issue on #834

**Comment by AlonsoGuevara** [comment]
I'll resolve this as we added some changes in version 0.2.1 to address this. But, please reopen if need, I'll be on the lookout! 
Btw, highly appreciate this type of dive deep and insights, really helps us improving the library together!
