### ISSUE TITLE
Community report grouping.

### ISSUE THREAD

**Issue by FatemaD1577** [microsoft/graphrag#841]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

I am trying to understand implementation of graph rag. I have gone through the documentation available and also through the git repo to understand the global query part. My understanding of the implementation is as follows:
1. We first create a graph based on the entities and relationships extracted.
2. Communities are then created by grouping closely related entities
3. At the next level community reports are created.
4. Whenever user query comes we shuffle the community reports randomly and group them
5. An intermediate response is generated for each group and a score is assigned to these groups based on the relevance of the answer to the user query
6. Responses with 0 score are filtered out and the remaining are passed on to the LLM for final response generation

Below are some of the doubts still not cleared:
1. Are community reports created at different levels to incrementally cover larger amount of information?
2. On what basis are the communities reports grouped? Is there any parameter to control number of community reports that will be included in one group?
3. Only responses with 0 score are filtered out or is there a threshold below which the responses will not be considered for final response generation?
5. On what basis are we scoring the intermediate response in relevance to user query? Is it using similarity search or any other method to determine the score?

Having an answer to these doubts will help me have more clarity on the process of the global querying part. 

Thank you in advance.

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by Xiyuche** [comment]
For the intermediate response score, this might be helpful, from the paper
<img width="691" alt="image" src="https://github.com/user-attachments/assets/308fe4d9-9b13-4867-8ae1-27319c19427d">

**Comment by natoverse** [comment]
Moving to Discussions: https://github.com/microsoft/graphrag/discussions/849
