### ISSUE TITLE
[Issue]: <title> how to configure this with azure-openai for GraphRAG? 

### ISSUE THREAD

**Issue by krishkarnan** [microsoft/graphrag#842]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [ ] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

encoding_model: cl100k_base
skip_workflows: []
llm:
  api_key: ${GRAPHRAG_API_KEY}
  type: azure_openai_chat
  model: gpt-4-turbo-preview
  model_supports_json: true # recommended if this is available for your model.
  api_base: https://openai-australiaeast-20240202.openai.azure.com/
  api_version: 2024-02-15-preview
  deployment_name: <azure_model_deployment_name>

parallelization:
  stagger: 0.3

async_mode: threaded # or asyncio

embeddings:
  
  async_mode: threaded # or asyncio
  llm:
    api_key: ${GRAPHRAG_API_KEY}
    type: azure_openai_embedding
    model: text-embedding-3-small
    api_base: https://openai-australiaeast-20240202.openai.azure.com/
    api_version: 2024-02-15-preview
    deployment_name: <azure_model_deployment_name>

chunks:
  size: 300
  overlap: 100
  group_by_columns: [id] # by default, we don't allow chunks to cross documents
    
input:
  type: file # or blob
  file_type: text # or csv
  base_dir: "input"
  file_encoding: utf-8
  file_pattern: ".*\\.txt$"

cache:
  type: file # or blob
  base_dir: "cache"

storage:
  type: file # or blob
  base_dir: "output/${timestamp}/artifacts"

reporting:
  type: file # or console, blob
  base_dir: "output/${timestamp}/reports"

entity_extraction:
  prompt: "prompts/entity_extraction.txt"
  entity_types: [organization,person,geo,event]
  max_gleanings: 1

summarize_descriptions:
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

claim_extraction:
  prompt: "prompts/claim_extraction.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

community_reports:
  prompt: "prompts/community_report.txt"
  max_length: 2000
  max_input_length: 8000

cluster_graph:
  max_cluster_size: 10

embed_graph:
  enabled: false # if true, will generate node2vec embeddings for nodes

umap:
  enabled: false # if true, will generate UMAP embeddings for nodes

snapshots:
  graphml: false
  raw_entities: false
  top_level_nodes: false

local_search:

global_search:

I tried this, but I get this error, but if I change OpenAI API key, no problem, the problem is only with Azure OpenAI API key.

❌ create_base_entity_graph
None
⠴ GraphRAG Indexer
├── Loading Input (InputFileType.text) - 1 files loaded (0 filtered) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00
├── create_base_text_units
├── create_base_extracted_entities
├── create_summarized_entities
└── create_base_entity_graph
❌ Errors occurred during the pipeline run, see logs for more details.

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
From your config it looks like you also need to supply the deployment name for your azure endpoint.

**Comment by krishkarnan** [comment]
@natoverse I have set "deployment_name: gpt-4-32k", but I still get the same error.

**Comment by natoverse** [comment]
Can you attach your output/<timestamp>reports/indexing-engine.log?

**Comment by Zochory** [comment]
Yes so it's not necessarly obvious, but you need to set the API version to where the 
![image](https://github.com/user-attachments/assets/18cc258a-a8ee-418c-8e08-0069d54e6075)
the url endpoint of your model end up even if it's 2023ish version instead of the 2024

**Comment by Zochory** [comment]
![image](https://github.com/user-attachments/assets/996db4a5-5405-4d51-bbf5-daf281087dc7)
And voilà !

**Comment by akashAD98** [comment]
can't we use opensource embedding model?

**Comment by krishkarnan** [comment]
@Zochory @natoverse Actually, I need to create a separate API for the Azure embedding model as well; I made a mistake and only used the Azure API for GPT-4-32k. Thank you for your help.

**Comment by krishkarnan** [comment]
![Screenshot 2024-08-12 095809](https://github.com/user-attachments/assets/aa91174e-deb8-4844-9c21-391b58238d8e)
I believe that if I use the GPT-$ 32K API, it will only be for the LLM model. 
![im2](https://github.com/user-attachments/assets/656ec59b-2dd4-438e-af2c-5246fc8995ad)
Embedding model API is different
