### ISSUE TITLE
pip install -r requirements.txt为啥一直报错呀[Issue]: <title> 

### ISSUE THREAD

**Issue by hezhi-lucky** [microsoft/graphrag#843]
### Is there an existing issue for this?

- [ ] I have searched the existing issues
- [ ] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
GraphRAG uses [poetry](https://python-poetry.org/) for dependency management, not requirements.txt. Once you have poetry installed on your system, please use `poetry install` to get the dependencies. See https://microsoft.github.io/graphrag/posts/developing/
