### ISSUE TITLE
[Feature Request]: <title>requesting for opensource large language models

### ISSUE THREAD

**Issue by luiaz34** [microsoft/graphrag#858]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this feature is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [X] I believe this is a legitimate feature request, not just a question. If this is a question, please use the Discussions area.

### Is your feature request related to a problem? Please describe.

i want to use opensoue large language models.

**Comment by natoverse** [comment]
Please see #657
