### ISSUE TITLE
[Bug]: Possible Bug: OverLength Error Occurs when Invoking LLM in the step of create_summarized_entities with Document whose Language is Not English

### ISSUE THREAD

**Issue by mzh1996** [microsoft/graphrag#866]
### Do you need to file an issue?

- [X] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [X] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

In /graphrag/index/graph/extractors/summarize/description_summary_extractor.py
![image](https://github.com/user-attachments/assets/a0cbfea9-81c9-470c-83e3-ba0f03ca41d4)

In the function of _summarize_descriptions_with_llm, the descriptions are inserted into the prompt by using 
json.dumps() without the args of ensure_ascii=False.
However, when the description is in some language (e.g. Chinese), the dumped result will be abnormal, making the tokenization result abnormal as well. Finally, the abnormal tokenization result can be over length when fed into LLM.

### Steps to reproduce

Use long document in Chinese.
Then, over length error may occur in the step of create_summarized_entities.

### Expected Behavior

when using language such as Chinese, it should use ```json.dumps(XXX, ensure_ascii=False)``` but not ```json.dumps(XXX)```

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:0.2.0
- Operating System:linux
- Python Version:3.10
- Related Issues:

**Comment by mzh1996** [comment]
Not sure if similar problems exist in other steps

**Comment by natoverse** [comment]
We have resolved several issues related to text encoding and JSON parsing that are rolled up into version [0.2.2](https://github.com/microsoft/graphrag/releases/tag/v0.2.2). Please try again with that version and re-open if this is still an issue.
