### ISSUE TITLE
The language of the community report is wrong.

### ISSUE THREAD

**Issue by yangxue-1** [microsoft/graphrag#869]
### Is there an existing issue for this?

- [ ] I have searched the existing issues
- [ ] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

The content of the input document is in Chinese, and the generated entities and relationships are also in Chinese. However, the community report is extracted into English and illusions occur. How can I solve this problem?

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
Please see #696 for language management
