### ISSUE TITLE
How to evaluate the extracted entity, relationship, and community reports?

### ISSUE THREAD

**Issue by yangxue-1** [microsoft/graphrag#904]
### Is there an existing issue for this?

- [ ] I have searched the existing issues
- [ ] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

How to evaluate the extracted entity, relationship, and community reports?

The result of the global search is always like this：I am sorry but I am unable to answer this question given the provided data.

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
There are some comments here about the technical aspects of the process: https://github.com/microsoft/graphrag/discussions/849

You can inspect the final output parquet files `create_final_entities.parquet`, `create_final_relationships.parquet` and `create_final_community_reports.parquet` to see if they are filled in and look reasonable. If you are seeing the "unable to answer question" message that most likely means the LLM was not satisfied that the reports were able to answer your question, and it filtered out all of them, and thus didn't have any reports to summarize.

**Comment by yangxue-1** [comment]
> There are some comments here about the technical aspects of the process: #849
> 
> You can inspect the final output parquet files `create_final_entities.parquet`, `create_final_relationships.parquet` and `create_final_community_reports.parquet` to see if they are filled in and look reasonable. If you are seeing the "unable to answer question" message that most likely means the LLM was not satisfied that the reports were able to answer your question, and it filtered out all of them, and thus didn't have any reports to summarize.


I'm dealing with a Chinese document. Why is there a string of exclamation marks in the extracted entity description?

**Comment by yangxue-1** [comment]
> There are some comments here about the technical aspects of the process: #849
> 
> You can inspect the final output parquet files `create_final_entities.parquet`, `create_final_relationships.parquet` and `create_final_community_reports.parquet` to see if they are filled in and look reasonable. If you are seeing the "unable to answer question" message that most likely means the LLM was not satisfied that the reports were able to answer your question, and it filtered out all of them, and thus didn't have any reports to summarize.

Is the create_summarized_entities.parquet file generated from summarize_descriptions.txt? When I read the cache/summarize_descriptions/ file, there is output, but create_summarized_entities.parquet shows nothing.

**Comment by yangxue-1** [comment]
> There are some comments here about the technical aspects of the process: #849
> 
> You can inspect the final output parquet files `create_final_entities.parquet`, `create_final_relationships.parquet` and `create_final_community_reports.parquet` to see if they are filled in and look reasonable. If you are seeing the "unable to answer question" message that most likely means the LLM was not satisfied that the reports were able to answer your question, and it filtered out all of them, and thus didn't have any reports to summarize.

The create_summarized_entities.parquet file shows that Nothing to show. Does this mean that the summarize_descriptions.txt file needs to be modified?

**Comment by yangxue-1** [comment]
> There are some comments here about the technical aspects of the process: #849
> 
> You can inspect the final output parquet files `create_final_entities.parquet`, `create_final_relationships.parquet` and `create_final_community_reports.parquet` to see if they are filled in and look reasonable. If you are seeing the "unable to answer question" message that most likely means the LLM was not satisfied that the reports were able to answer your question, and it filtered out all of them, and thus didn't have any reports to summarize.

The description of entities in the create_final_entities.parquet file is incorrect. Some entities contain garbled characters, and some descriptions are inconsistent with the entities.
