### ISSUE TITLE
[Issue]: <title> GraphRAG supports English, but does it support other languages, such as Chinese?

### ISSUE THREAD

**Issue by zhangjiuyang1993** [microsoft/graphrag#916]
### Is there an existing issue for this?

- [ ] I have searched the existing issues
- [ ] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by luneice** [comment]
需要把很多 prompt 进行翻译，翻译之后效果好一些。但是总是会在提取实体的那步出错。目前尝试了N次，就成功了三次。

**Comment by novem33** [comment]
好想知道成功了三次是調整那些內容，微軟這整個架構有點巨大!!!

**Comment by novem33** [comment]
> 需要把很多 prompt 进行翻译，翻译之后效果好一些。但是总是会在提取实体的那步出错。目前尝试了N次，就成功了三次。

好想知道成功了三次是調整那些內容，微軟這整個架構有點巨大!!!

**Comment by 6ixGODD** [comment]
> 需要把很多 prompt 进行翻译，翻译之后效果好一些。但是总是会在提取实体的那步出错。目前尝试了N次，就成功了三次。

@luneice 把prompt全改成中文我没试过，不过你倒是可以试试在entity_extraction.txt中的第三步和第四步把English换成Chinese，别的保持不变，直接用Prompt Tuning也是这么搞的，再提供些示例。我试了效果还行。
要么继承BaseLLM类实现一个中文大模型的API，比如文心或者kimi，替换openai GPT，再用全中文的prompt试试。我正打算后面这么做做看

**Comment by natoverse** [comment]
Please see #696

**Comment by night666e** [comment]
> > 需要把很多 prompt 进行翻译，翻译之后效果好一些。但是总是会在提取实体的那步出错。目前尝试了N次，就成功了三次。
> 
> @luneice 把prompt全改成中文我没试过，不过你倒是可以试试在entity_extraction.txt中的第三步和第四步把English换成Chinese，别的保持不变，直接用Prompt Tuning也是这么搞的，再提供些示例。我试了效果还行。 要么继承BaseLLM类实现一个中文大模型的API，比如文心或者kimi，替换openai GPT，再用全中文的prompt试试。我正打算后面这么做做看

有效果吗，为什么我改用提示词就管道错误
