### ISSUE TITLE
[Feature Request]: Add support for Couchbase Vector Store

### ISSUE THREAD

**Issue by deniswsrosa** [microsoft/graphrag#921]
### Do you need to file an issue?

- [X] I have searched the existing issues and this feature is not already filed.
- [X] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [X] I believe this is a legitimate feature request, not just a question. If this is a question, please use the Discussions area.

### Is your feature request related to a problem? Please describe.

I have been playing with the framework and I wonder if it is okay to push a PR adding support for Couchbase as a Vector store

### Describe the solution you'd like

I will add the implementation by myself if this is ok for the mantainers.

**Comment by AlonsoGuevara** [comment]
Hi!

Sure thing, contributions are welcome :)
