### ISSUE TITLE
[Issue]: llama-index-core (0.10.65) depends on nltk (>=3.8.2) and tenacity (>=8.2.0,<8.4.0 || >8.4.0,<9.0.0)

### ISSUE THREAD

**Issue by asynchat** [microsoft/graphrag#929]
### Is there an existing issue for this?

- [ ] I have searched the existing issues
- [ ] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

Because no versions of graphrag match >0.2.1,<0.2.2 || >0.2.2,<0.3.0
 and graphrag (0.2.1) depends on nltk (3.8.1), graphrag (>=0.2.1,<0.2.2 || >0.2.2,<0.3.0) requires nltk (3.8.1).
And because graphrag (0.2.2) depends on tenacity (>=9.0.0,<10.0.0)
 and llama-index-core (0.10.65) depends on nltk (>=3.8.2), if graphrag (>=0.2.1,<0.3.0) and llama-index-core (0.10.65) then tenacity (>=9.0.0,<10.0.0).
And because llama-index-core (0.10.65) depends on tenacity (>=8.2.0,<8.4.0 || >8.4.0,<9.0.0)
 and no versions of llama-index-core match >0.10.65,<0.11.0, graphrag (>=0.2.1,<0.3.0) is incompatible with llama-index-core (>=0.10.65,<0.11.0).

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version: v0.2.2 v0.3.0
- Operating System: MACOS
- Python Version: 3.11
- Related Issues:

**Comment by RobinBially** [comment]
Thanks for the issue! I have the same issue with langchain.
