### ISSUE TITLE
How to get reference documents of the global-search-result 

### ISSUE THREAD

**Issue by XiaoTongDeng** [microsoft/graphrag#930]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [ ] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

I want to know how to get reference documents of the global-search-result? 

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
Moving to discussions with a reply: https://github.com/microsoft/graphrag/discussions/931
