### ISSUE TITLE
The content of the file generated in the index process is incorrect.

### ISSUE THREAD

**Issue by yangxue-1** [microsoft/graphrag#936]
### Is there an existing issue for this?

- [ ] I have searched the existing issues
- [ ] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

Q1:
The description of entities in the create_final_entities.parquet file is incorrect. Some entities contain garbled characters, and some descriptions are inconsistent with the entities.

Q2:
The create_summarized_entities.parquet file shows that Nothing to show. Does this mean that the summarize_descriptions.txt file needs to be modified?

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by AlonsoGuevara** [comment]
Hi!
Can you please provide more details?
- Language of your inputs?
- Are you using prompt tuning?
- Model or config file.

**Comment by yangxue-1** [comment]
> Hi! Can you please provide more details?
> 
>     * Language of your inputs?
> 
>     * Are you using prompt tuning?
> 
>     * Model or config file.

- The input file is in Chinese.
- Yes,use prompt tuning.
- LLM:qwen2-7b,embedding:o200k_base

**Comment by natoverse** [comment]
Routing this to #696. Language issues are very difficult for us to diagnose. I also suggest making sure you are on version 0.3.0, which does include some improved handling of language encoding.
