### ISSUE TITLE
[Issue]: <title> Detailed explanation of the seeding. yaml parameter

### ISSUE THREAD

**Issue by XiaoTongDeng** [microsoft/graphrag#948]
### Is there an existing issue for this?

- [ ] I have searched the existing issues
- [ ] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

There is confusion regarding the parameters of local_dearch and globalis_search in seeding.ml. Could you please explain in detail the meanings of these parameters for me? For example, the value range of llm_top_p is 0~1, does this mean it is a percentage of the content?
![image](https://github.com/user-attachments/assets/18cdc46c-1cb2-4c7e-a11c-cd19796b9b9e)

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
This is passed through to OpenAI directly - see the docs here: https://platform.openai.com/docs/api-reference/chat/create#chat-create-top_p
