### ISSUE TITLE
[Issue]: How to enable Entity Resolution

### ISSUE THREAD

**Issue by unknown918** [microsoft/graphrag#962]
### Do you need to file an issue?

- [X] I have searched the existing issues and this bug is not already filed.
- [X] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the issue

According to the documentation, there should be a step which is not by default called `Entity Resolution`, but I didn't seem to find this option in the config files.

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version: v0.3.0
- Operating System: macOS 14.5
- Python Version: 3.11
- Related Issues:

**Comment by natoverse** [comment]
Please see here: https://github.com/microsoft/graphrag/discussions/778. The docs have been updated, but we just realized the gh-pages deploy was failing. Should reflect the removed content shortly.
