### ISSUE TITLE
create_summarized_entities.parquet has no content

### ISSUE THREAD

**Issue by yangxue-1** [microsoft/graphrag#964]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the issue

View of create_summarized_entities.parquet shows nothing to show.

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
Do you see any errors in your indexing-engine.log that could help diagnose?
