### ISSUE TITLE
httpx.ConnectError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by hanyimei** [microsoft/graphrag#971]
### Do you need to file an issue?

- [X] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the issue

我卡在 create_final_entities这一步，报错信息显示：httpx.ConnectError: [Errno 111] Connection refused，在尝试连接到服务器时被拒绝了。但我用crul命令访问两个api的时候是可以正常使用的，有友友遇到同样情况的吗

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by hanyimei** [comment]
该问题已解决，针对报错日志显示：datashaper.workflow.workflow ERROR Error executing verb "text_embed" in create_final_entities: [Errno 111] Connection refused
在代码文件\graphrag\index\workflows\v1\create_final_entities.py中，将skip_name_embedding和skip_description_embedding设置为True，即可解决报错，针对此问题若有其他解决方案欢迎交流。

**Comment by DStarEpoch** [comment]
> 该问题已解决，针对报错日志显示：datashaper.workflow.workflow ERROR Error executing verb "text_embed" in create_final_entities: [Errno 111] Connection refused 在代码文件\graphrag\index\workflows\v1\create_final_entities.py中，将skip_name_embedding和skip_description_embedding设置为True，即可解决报错，针对此问题若有其他解决方案欢迎交流。

+1，感谢，同问题已解决
