### ISSUE TITLE
[Feature Request]: Integrate with Llamaindex

### ISSUE THREAD

**Issue by moghadas76** [microsoft/graphrag#985]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this feature is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate feature request, not just a question. If this is a question, please use the Discussions area.

### Is your feature request related to a problem? Please describe.

How to Integrate with Llamaindex?

**Comment by AlonsoGuevara** [comment]
Hi!
We are consolidating alternate model issues here: https://github.com/microsoft/graphrag/issues/657
